export const AREAS = [
  { name: '線上', label: '線上' },
  { name: '台北市', label: '台北市' },
  { name: '新北市', label: '新北市' },
  { name: '基隆市', label: '基隆市' },
  { name: '桃園市', label: '桃園市' },
  { name: '新竹市', label: '新竹市' },
  { name: '新竹縣', label: '新竹縣' },
  { name: '苗栗縣', label: '苗栗縣' },
  { name: '台中市', label: '台中市' },
  { name: '南投縣', label: '南投縣' },
  { name: '彰化縣', label: '彰化縣' },
  { name: '雲林縣', label: '雲林縣' },
  { name: '嘉義市', label: '嘉義市' },
  { name: '嘉義縣', label: '嘉義縣' },
  { name: '台南市', label: '台南市' },
  { name: '高雄市', label: '高雄市' },
  { name: '屏東縣', label: '屏東縣' },
  { name: '台東縣', label: '台東縣' },
  { name: '花蓮縣', label: '花蓮縣' },
  { name: '宜蘭縣', label: '宜蘭縣' },
  { name: '澎湖縣', label: '澎湖縣' },
  { name: '金門縣', label: '金門縣' },
  { name: '連江縣', label: '連江縣' },
];
