import type { CategoryType, IAction } from "../types";

/**
 * 離線 / API 失敗時的備用靜態行動建議。
 * 每個分類提供一組通用行動建議（3 個等級）。
 */
export const fallbackActionsMap = new Map<CategoryType, IAction[]>([
	[
		"interest",
		[
			{
				id: "interest-beginner-fallback",
				categoryId: "interest",
				level: "beginner",
				title: "探索你的興趣清單",
				description: "花 10 分鐘列出你感興趣但一直沒開始的事，選出最想嘗試的一件。",
				duration: "約 10 分鐘",
				tip: "不需要完美，先列出來就是好的開始。",
				rationale: "將探索綁定在固定作息後（如晚餐後），能大幅提高執行機率。",
			},
			{
				id: "interest-intermediate-fallback",
				categoryId: "interest",
				level: "intermediate",
				title: "制定你的興趣學習計畫",
				description: "針對你最感興趣的一件事，搜尋 3 個學習資源並安排本週學習時間。",
				duration: "約 25 分鐘",
				tip: "具體的計畫比空想更容易執行。",
				rationale: "有明確的資源和時間表，比單純想「有空再做」更容易堅持。",
			},
			{
				id: "interest-advanced-fallback",
				categoryId: "interest",
				level: "advanced",
				title: "完成你的第一個小作品",
				description: "動手做出一個可展示的小成果，無論多簡單都算數。",
				duration: "約 45 分鐘",
				tip: "完成比完美重要，先做出來再慢慢改進。",
				rationale: "看到具體成果會大幅增強動力，形成正向循環。",
			},
		],
	],
	[
		"social",
		[
			{
				id: "social-beginner-fallback",
				categoryId: "social",
				level: "beginner",
				title: "傳送一則關心訊息",
				description: "選一位你許久沒聯繫的朋友或家人，傳一則簡單的問候訊息。",
				duration: "約 5 分鐘",
				tip: "不需要特別的理由，一句「最近好嗎」就很棒了。",
				rationale: "小小的行動就能維繫關係，降低門檻才能持續。",
			},
			{
				id: "social-intermediate-fallback",
				categoryId: "social",
				level: "intermediate",
				title: "約一位朋友見面",
				description: "主動邀約一位朋友喝杯咖啡或散步，進行一次面對面交流。",
				duration: "約 60 分鐘",
				tip: "面對面的交流品質遠超過文字訊息。",
				rationale: "定期的社交互動對心理健康有顯著正面影響。",
			},
			{
				id: "social-advanced-fallback",
				categoryId: "social",
				level: "advanced",
				title: "參加一場社群活動",
				description: "報名參加一場線上或線下的社群活動，認識新朋友。",
				duration: "約 90 分鐘",
				tip: "踏出舒適圈是拓展人脈的第一步。",
				rationale: "新環境帶來新刺激，有助於拓展視野和社交圈。",
			},
		],
	],
	[
		"health",
		[
			{
				id: "health-beginner-fallback",
				categoryId: "health",
				level: "beginner",
				title: "做 5 分鐘伸展操",
				description: "起床後或睡前花 5 分鐘做簡單的全身伸展。",
				duration: "約 5 分鐘",
				tip: "不需要瑜伽墊，站著或坐著都能做。",
				rationale: "綁定在起床或睡前的固定作息，養成習慣更容易。",
			},
			{
				id: "health-intermediate-fallback",
				categoryId: "health",
				level: "intermediate",
				title: "完成 20 分鐘居家運動",
				description: "跟著一支運動影片完成 20 分鐘的居家訓練。",
				duration: "約 20 分鐘",
				tip: "找一支你喜歡的 YouTuber 運動影片，跟著做就對了。",
				rationale: "規律運動能提升精神和專注力，對學習和工作都有幫助。",
			},
			{
				id: "health-advanced-fallback",
				categoryId: "health",
				level: "advanced",
				title: "準備一份健康餐",
				description: "自己動手準備一份營養均衡的餐點，記錄食材和做法。",
				duration: "約 40 分鐘",
				tip: "從簡單的沙拉或三明治開始，不需要高難度料理。",
				rationale: "親手準備食物能更了解自己的飲食，建立更健康的習慣。",
			},
		],
	],
	[
		"academic",
		[
			{
				id: "academic-beginner-fallback",
				categoryId: "academic",
				level: "beginner",
				title: "閱讀 15 分鐘",
				description: "選一本你感興趣的書或文章，專注閱讀 15 分鐘。",
				duration: "約 15 分鐘",
				tip: "設定計時器，時間到就可以停，不需要壓力。",
				rationale: "每天 15 分鐘，一個月就能讀完一本書。",
			},
			{
				id: "academic-intermediate-fallback",
				categoryId: "academic",
				level: "intermediate",
				title: "完成一堂線上課程章節",
				description: "選擇一門你正在學習的線上課程，完成一個章節並做筆記。",
				duration: "約 30 分鐘",
				tip: "做筆記能幫助記憶，哪怕只是簡單的重點摘要。",
				rationale: "系統化學習比零散瀏覽更有效率。",
			},
			{
				id: "academic-advanced-fallback",
				categoryId: "academic",
				level: "advanced",
				title: "教別人你學到的東西",
				description: "把今天學到的知識用自己的話解釋給朋友或寫成筆記分享。",
				duration: "約 45 分鐘",
				tip: "教學相長，能教會別人代表你真的懂了。",
				rationale: "費曼學習法證明，教學是最有效的學習方式。",
			},
		],
	],
	[
		"work",
		[
			{
				id: "work-beginner-fallback",
				categoryId: "work",
				level: "beginner",
				title: "整理明天的待辦清單",
				description: "花 10 分鐘列出明天最重要的 3 件事，並排好優先順序。",
				duration: "約 10 分鐘",
				tip: "只列 3 件最重要的事，不要貪多。",
				rationale: "睡前整理隔天計畫，能減少焦慮並提高執行力。",
			},
			{
				id: "work-intermediate-fallback",
				categoryId: "work",
				level: "intermediate",
				title: "學習一個新工具或技巧",
				description: "花 20 分鐘學習一個能提升工作效率的工具或快捷鍵。",
				duration: "約 20 分鐘",
				tip: "一次學一個就好，確保真的記住並使用。",
				rationale: "小技巧的累積能大幅提升長期工作效率。",
			},
			{
				id: "work-advanced-fallback",
				categoryId: "work",
				level: "advanced",
				title: "完成一個專業作品集項目",
				description: "針對你的專業領域，完成一個可展示的小型作品或案例。",
				duration: "約 60 分鐘",
				tip: "不需要完美，能展示你的能力和思考過程就好。",
				rationale: "累積作品集是建立專業形象最有效的方式。",
			},
		],
	],
	[
		"finance",
		[
			{
				id: "finance-beginner-fallback",
				categoryId: "finance",
				level: "beginner",
				title: "記錄今天的花費",
				description: "把今天所有的消費記錄下來，分類整理。",
				duration: "約 5 分鐘",
				tip: "可以用手機備忘錄或記帳 App，重點是養成記錄習慣。",
				rationale: "了解錢花在哪裡，是理財的第一步。",
			},
			{
				id: "finance-intermediate-fallback",
				categoryId: "finance",
				level: "intermediate",
				title: "閱讀一篇理財文章",
				description: "花 20 分鐘閱讀一篇關於儲蓄、投資或預算管理的文章。",
				duration: "約 20 分鐘",
				tip: "從基礎觀念開始，不要一開始就追求高報酬策略。",
				rationale: "理財知識的累積能幫助你做出更好的財務決策。",
			},
			{
				id: "finance-advanced-fallback",
				categoryId: "finance",
				level: "advanced",
				title: "制定月度預算計畫",
				description: "根據過去的消費記錄，制定下個月的收支預算並設定儲蓄目標。",
				duration: "約 40 分鐘",
				tip: "預算不是限制，而是幫你把錢花在真正重要的地方。",
				rationale: "有計畫的消費比無意識的花費更能帶來滿足感。",
			},
		],
	],
]);

export function getFallbackActions(categoryId: CategoryType): IAction[] {
	return fallbackActionsMap.get(categoryId) ?? [];
}
