import type { IAction } from "../types";

/**
 * 每個 tag 對應的靜態行動建議（初學 / 中級 / 進階）。
 * 當 Worker API 無法使用時，根據使用者選的 tag 直接回傳對應行動。
 */
export const tagActionsMap = new Map<string, IAction[]>([
  // ─── interest ───
  [
    "學會鉤針",
    [
      {
        id: "tag-學會鉤針-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "學會基本鎖針",
        description: "跟著教學影片學會起針和鎖針，完成一條 10 公分的練習鏈。",
        duration: "約 15 分鐘",
        tip: "先用粗毛線和大鉤針練習，比較容易上手。",
        rationale: "鎖針是所有鉤針的基礎，學會它就能開始做簡單的作品。",
      },
      {
        id: "tag-學會鉤針-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "鉤出一個杯墊",
        description: "用短針和長針技法，鉤出一個圓形或方形杯墊。",
        duration: "約 30 分鐘",
        tip: "選一個你喜歡的顏色，完成後放在桌上會很有成就感。",
        rationale: "杯墊是小而完整的作品，能快速建立信心。",
      },
      {
        id: "tag-學會鉤針-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "挑戰鉤一個小玩偶",
        description: "跟著 Amigurumi 教學，鉤出一個簡單的動物玩偶。",
        duration: "約 60 分鐘",
        tip: "從最簡單的圓球造型開始，慢慢加上五官和四肢。",
        rationale: "完成一個立體作品會大幅提升動力和技巧。",
      },
    ],
  ],
  [
    "登上百岳",
    [
      {
        id: "tag-登上百岳-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "研究一座入門百岳",
        description: "花 15 分鐘查詢一座適合新手的百岳路線、交通和裝備需求。",
        duration: "約 15 分鐘",
        tip: "合歡山群峰、石門山是熱門的入門選擇。",
        rationale: "事前研究能降低焦慮，讓出發更有信心。",
      },
      {
        id: "tag-登上百岳-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "完成一次郊山健行",
        description: "選一條來回 2-3 小時的郊山步道，實際走一趟測試體力。",
        duration: "約 2-3 小時",
        tip: "帶足水和簡單行動糧，穿合腳的運動鞋。",
        rationale: "用郊山練腳力，為百岳做好體能準備。",
      },
      {
        id: "tag-登上百岳-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "制定百岳攀登計畫",
        description: "選定目標百岳，規劃行程、交通、住宿，列出所需裝備清單。",
        duration: "約 45 分鐘",
        tip: "找有經驗的山友一起規劃，安全第一。",
        rationale: "完整的計畫是成功登頂的關鍵。",
      },
    ],
  ],
  [
    "畫出油畫作品",
    [
      {
        id: "tag-畫出油畫作品-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "認識油畫基本工具",
        description: "花 15 分鐘了解油畫顏料、畫筆、調色盤和畫布的基本用法。",
        duration: "約 15 分鐘",
        tip: "初學可以先買基礎色（紅黃藍白黑），不用一次買齊。",
        rationale: "了解工具才能安心下筆，減少挫折感。",
      },
      {
        id: "tag-畫出油畫作品-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "完成一幅色彩練習",
        description: "用三原色調出至少 6 種不同色彩，畫在畫布上練習混色。",
        duration: "約 30 分鐘",
        tip: "油畫的魅力在於混色，大膽嘗試不同比例。",
        rationale: "掌握混色是油畫最核心的技巧。",
      },
      {
        id: "tag-畫出油畫作品-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "畫一幅簡單的靜物畫",
        description: "擺好一組簡單的靜物（水果或杯子），用油畫完成一幅小作品。",
        duration: "約 60 分鐘",
        tip: "先用鉛筆打稿，再上色，不求完美但求完成。",
        rationale: "完成一幅作品的成就感會推動你繼續畫下去。",
      },
    ],
  ],
  [
    "研究子彈筆記",
    [
      {
        id: "tag-研究子彈筆記-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "了解子彈筆記核心概念",
        description: "花 15 分鐘了解子彈筆記的索引、快速紀錄和符號系統。",
        duration: "約 15 分鐘",
        tip: "不需要華麗的版面，簡單的符號系統就能開始。",
        rationale: "先理解原理，再開始實作，避免走彎路。",
      },
      {
        id: "tag-研究子彈筆記-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "建立你的第一本子彈筆記",
        description: "準備一本空白筆記本，建立索引頁、未來紀錄和本月紀錄。",
        duration: "約 25 分鐘",
        tip: "用任何筆記本都行，重點是開始寫。",
        rationale: "動手做比一直研究更能理解子彈筆記的價值。",
      },
      {
        id: "tag-研究子彈筆記-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "設計個人化的追蹤頁",
        description: "根據你的需求設計一個習慣追蹤、閱讀紀錄或理財追蹤頁面。",
        duration: "約 40 分鐘",
        tip: "從你最想追蹤的一件事開始，不要一次設計太多。",
        rationale: "個人化的追蹤頁讓子彈筆記真正為你服務。",
      },
    ],
  ],
  [
    "iPhone 攝影技巧",
    [
      {
        id: "tag-iPhone攝影技巧-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "學會構圖三分法",
        description: "開啟 iPhone 格線輔助，練習用三分法拍攝 5 張照片。",
        duration: "約 15 分鐘",
        tip: "到「設定 > 相機」開啟格線，把主體放在交叉點上。",
        rationale: "三分法是最基礎也最實用的構圖技巧。",
      },
      {
        id: "tag-iPhone攝影技巧-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "練習光線運用",
        description: "在不同光線條件下（順光、逆光、側光）各拍 3 張照片並比較效果。",
        duration: "約 20 分鐘",
        tip: "黃金時刻（日出後和日落前一小時）的光線最美。",
        rationale: "攝影就是光的藝術，掌握光線就掌握了一半。",
      },
      {
        id: "tag-iPhone攝影技巧-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "拍攝並後製一組作品",
        description: "選一個主題拍攝 10 張照片，挑出最好的 3 張用內建編輯器調整。",
        duration: "約 40 分鐘",
        tip: "調整曝光、對比和飽和度就能讓照片大幅提升。",
        rationale: "有主題的拍攝能訓練你的攝影眼。",
      },
    ],
  ],
  [
    "一週一影評",
    [
      {
        id: "tag-一週一影評-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "寫下觀影心得",
        description: "看完一部電影後，花 10 分鐘寫下你的感受和印象最深的場景。",
        duration: "約 10 分鐘",
        tip: "不需要專業用語，用自己的話寫就好。",
        rationale: "先養成「看完就寫」的習慣，是影評的第一步。",
      },
      {
        id: "tag-一週一影評-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "分析電影的敘事結構",
        description: "重看一部喜歡的電影，記錄它的三幕結構和轉折點。",
        duration: "約 30 分鐘",
        tip: "注意開場、衝突升級、高潮和結尾的安排。",
        rationale: "理解敘事結構能讓你的影評更有深度。",
      },
      {
        id: "tag-一週一影評-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "完成一篇 500 字影評",
        description: "選一部本週看的電影，寫一篇包含劇情分析、技術評價和推薦理由的影評。",
        duration: "約 45 分鐘",
        tip: "先列大綱再寫，結構會更清晰。",
        rationale: "完整的影評能鍛鍊你的批判思考和寫作能力。",
      },
    ],
  ],
  [
    "韓系化妝進階班",
    [
      {
        id: "tag-韓系化妝進階班-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "學會韓系底妝技巧",
        description: "跟著教學學習韓系水光肌底妝，練習薄透自然的上妝手法。",
        duration: "約 15 分鐘",
        tip: "關鍵是少量多次，一層一層疊上去。",
        rationale: "底妝是整體妝容的基礎，韓系妝的重點就是好膚質感。",
      },
      {
        id: "tag-韓系化妝進階班-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "練習韓系眼妝",
        description: "用大地色眼影練習韓系清透眼妝，搭配自然的眼線畫法。",
        duration: "約 25 分鐘",
        tip: "韓系眼妝重點是暈染自然，避免太銳利的線條。",
        rationale: "眼妝是妝容的靈魂，掌握後整體質感大幅提升。",
      },
      {
        id: "tag-韓系化妝進階班-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "完成一個完整韓系妝容",
        description: "從底妝到唇妝完成一整套韓系妝容，拍照記錄成果。",
        duration: "約 40 分鐘",
        tip: "最後用定妝噴霧固定，拍照對比妝前妝後。",
        rationale: "完成全妝能讓你看到整體效果，建立自信。",
      },
    ],
  ],
  [
    "寫小說",
    [
      {
        id: "tag-寫小說-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "寫一段 200 字的場景描寫",
        description: "選一個你熟悉的場景（咖啡廳、教室、公園），用 200 字描繪它。",
        duration: "約 15 分鐘",
        tip: "加入五感描寫（看到、聽到、聞到），場景會更生動。",
        rationale: "場景描寫是小說的基本功，短篇練習降低壓力。",
      },
      {
        id: "tag-寫小說-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "設計一個角色人物誌",
        description: "為你的故事設計一個角色，寫下外貌、性格、背景和動機。",
        duration: "約 25 分鐘",
        tip: "好角色需要有缺點和矛盾，完美的角色反而不真實。",
        rationale: "角色是故事的核心，先建立角色再發展劇情更順暢。",
      },
      {
        id: "tag-寫小說-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "完成一篇 1000 字短篇故事",
        description: "用你設計的角色和場景，寫一篇有開頭、衝突和結尾的短篇故事。",
        duration: "約 60 分鐘",
        tip: "先寫完再修改，不要邊寫邊改。",
        rationale: "完成一篇故事比寫出完美的第一章更重要。",
      },
    ],
  ],
  [
    "學烏克麗麗",
    [
      {
        id: "tag-學烏克麗麗-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "學會 C 和弦和基本刷法",
        description: "學會按 C 和弦並練習基本的下刷節奏，持續 10 分鐘。",
        duration: "約 15 分鐘",
        tip: "手指按弦會痛是正常的，持續練習就會習慣。",
        rationale: "C 和弦是最基礎的和弦，學會它就能彈簡單的歌。",
      },
      {
        id: "tag-學烏克麗麗-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "練習四個常用和弦轉換",
        description: "練習 C、G、Am、F 四個和弦的流暢轉換，搭配節奏刷弦。",
        duration: "約 25 分鐘",
        tip: "慢慢來，先求準確再求速度。",
        rationale: "這四個和弦能彈大部分流行歌曲。",
      },
      {
        id: "tag-學烏克麗麗-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "完整彈唱一首歌",
        description: "選一首你喜歡的歌，練習完整彈唱，錄音記錄進步。",
        duration: "約 40 分鐘",
        tip: "先選和弦簡單的歌，推薦從兒歌或簡單流行歌開始。",
        rationale: "能完整彈唱一首歌會帶來巨大的成就感。",
      },
    ],
  ],
  [
    "iPad 畫畫",
    [
      {
        id: "tag-iPad畫畫-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "熟悉繪圖 App 基本工具",
        description: "打開 Procreate 或其他繪圖 App，花 15 分鐘試用畫筆、橡皮擦和圖層功能。",
        duration: "約 15 分鐘",
        tip: "先隨意塗鴉，熟悉手感最重要。",
        rationale: "了解工具才能專注在創作上。",
      },
      {
        id: "tag-iPad畫畫-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "臨摹一張簡單的插畫",
        description: "找一張你喜歡的簡單插畫，用 iPad 臨摹練習線條和上色。",
        duration: "約 30 分鐘",
        tip: "臨摹是學畫最有效的方式之一，不用覺得不好意思。",
        rationale: "透過臨摹學習別人的構圖和配色技巧。",
      },
      {
        id: "tag-iPad畫畫-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "畫一張原創插畫",
        description: "選一個主題，從草稿到上色完成一張你自己的插畫作品。",
        duration: "約 60 分鐘",
        tip: "先用簡單的形狀打稿，再慢慢細化。",
        rationale: "原創作品是最好的學習成果展現。",
      },
    ],
  ],
  [
    "動手做便當",
    [
      {
        id: "tag-動手做便當-beginner",
        categoryId: "interest",
        level: "beginner",
        title: "規劃一週便當菜單",
        description: "花 15 分鐘規劃本週 3 天的便當菜色，列出需要的食材。",
        duration: "約 15 分鐘",
        tip: "從簡單的一主菜兩配菜開始，不要太複雜。",
        rationale: "有計畫才不會臨時不知道做什麼而放棄。",
      },
      {
        id: "tag-動手做便當-intermediate",
        categoryId: "interest",
        level: "intermediate",
        title: "做一個簡單的便當",
        description: "準備一個包含主食、主菜和配菜的便當，練習擺盤。",
        duration: "約 30 分鐘",
        tip: "前一晚先備料，早上只需要加熱和裝盒。",
        rationale: "親手做的便當既省錢又健康。",
      },
      {
        id: "tag-動手做便當-advanced",
        categoryId: "interest",
        level: "advanced",
        title: "挑戰一款造型便當",
        description: "用簡單的食材做出有造型的便當（如卡通飯糰），拍照記錄。",
        duration: "約 50 分鐘",
        tip: "海苔剪刀和食物模具是好幫手。",
        rationale: "漂亮的便當會讓吃飯變成一件開心的事。",
      },
    ],
  ],

  // ─── social ───
  [
    "每週約一位朋友",
    [
      {
        id: "tag-每週約一位朋友-beginner",
        categoryId: "social",
        level: "beginner",
        title: "傳一則問候訊息",
        description: "選一位最近沒聯繫的朋友，傳一則簡單的問候或分享一篇有趣的文章。",
        duration: "約 5 分鐘",
        tip: "不用想太多理由，直接傳就對了。",
        rationale: "一則訊息就能重新啟動一段關係。",
      },
      {
        id: "tag-每週約一位朋友-intermediate",
        categoryId: "social",
        level: "intermediate",
        title: "約朋友喝杯咖啡",
        description: "主動邀約一位朋友本週找個時間喝杯咖啡或吃個飯。",
        duration: "約 60 分鐘",
        tip: "提供具體的時間和地點選項，對方更容易答應。",
        rationale: "面對面交流的品質遠超過線上聊天。",
      },
      {
        id: "tag-每週約一位朋友-advanced",
        categoryId: "social",
        level: "advanced",
        title: "組織一場小型聚會",
        description: "邀請 3-5 位朋友一起吃飯或做一件有趣的事（桌遊、散步、野餐）。",
        duration: "約 2-3 小時",
        tip: "不用準備太多，重點是大家聚在一起。",
        rationale: "主動組織聚會能強化你在社交圈中的連結角色。",
      },
    ],
  ],
  [
    "練習傾聽技巧",
    [
      {
        id: "tag-練習傾聽技巧-beginner",
        categoryId: "social",
        level: "beginner",
        title: "練習不打斷的對話",
        description: "在今天的一次對話中，專注聽對方說完再回應，不中途插話。",
        duration: "約 10 分鐘",
        tip: "當想插話時，先在心裡默數三秒。",
        rationale: "不打斷是傾聽最基本也最重要的練習。",
      },
      {
        id: "tag-練習傾聽技巧-intermediate",
        categoryId: "social",
        level: "intermediate",
        title: "練習重述對方的話",
        description: "在對話中練習用自己的話重述對方的意思，確認你理解正確。",
        duration: "約 15 分鐘",
        tip: "試試「你的意思是...對嗎？」這個句型。",
        rationale: "重述能讓對方感受到被理解，也避免誤解。",
      },
      {
        id: "tag-練習傾聽技巧-advanced",
        categoryId: "social",
        level: "advanced",
        title: "進行一場深度傾聽對話",
        description: "和一位朋友進行 30 分鐘的深度對話，專注在理解感受而非解決問題。",
        duration: "約 30 分鐘",
        tip: "多問「你當時的感覺是什麼？」而非「你應該怎麼做」。",
        rationale: "深度傾聽能大幅提升關係品質。",
      },
    ],
  ],
  [
    "加入社團活動",
    [
      {
        id: "tag-加入社團活動-beginner",
        categoryId: "social",
        level: "beginner",
        title: "搜尋感興趣的社團",
        description: "花 15 分鐘在社群平台搜尋你所在地區或線上的興趣社團。",
        duration: "約 15 分鐘",
        tip: "Facebook 社團、Meetup 或大學社團都是好選擇。",
        rationale: "先了解有哪些選擇，才能找到最適合自己的。",
      },
      {
        id: "tag-加入社團活動-intermediate",
        categoryId: "social",
        level: "intermediate",
        title: "參加一次社團聚會",
        description: "報名並參加一場線上或線下的社團活動，認識新朋友。",
        duration: "約 90 分鐘",
        tip: "第一次去很正常會緊張，準備一兩個自我介紹的話題。",
        rationale: "踏出第一步是最難也最重要的。",
      },
      {
        id: "tag-加入社團活動-advanced",
        categoryId: "social",
        level: "advanced",
        title: "在社團中主動承擔一個角色",
        description: "主動提議幫忙社團的一件事，例如拍照記錄、帶新人或協助活動。",
        duration: "約 60 分鐘",
        tip: "從小事開始，不用一次扛太多。",
        rationale: "主動付出能更快融入團體，也能認識更多人。",
      },
    ],
  ],
  [
    "學會拒絕的藝術",
    [
      {
        id: "tag-學會拒絕的藝術-beginner",
        categoryId: "social",
        level: "beginner",
        title: "準備三個禮貌拒絕的說法",
        description: "寫下三個你能自在說出口的拒絕用語，例如「謝謝你的邀請，但我這次先不參加」。",
        duration: "約 10 分鐘",
        tip: "拒絕不需要長篇理由，簡短真誠就好。",
        rationale: "事先準備好說法，實際需要時才不會慌張。",
      },
      {
        id: "tag-學會拒絕的藝術-intermediate",
        categoryId: "social",
        level: "intermediate",
        title: "練習一次說不",
        description: "在今天遇到不想答應的請求時，用你準備好的說法禮貌拒絕。",
        duration: "約 5 分鐘",
        tip: "拒絕後可能會不舒服，但這種感覺會慢慢消退。",
        rationale: "每一次練習都在強化你的界線意識。",
      },
      {
        id: "tag-學會拒絕的藝術-advanced",
        categoryId: "social",
        level: "advanced",
        title: "反思你的界線模式",
        description: "回顧最近一個月，列出你勉強答應的事，分析為什麼難以拒絕。",
        duration: "約 30 分鐘",
        tip: "寫下來會比想的更清楚，也更容易發現模式。",
        rationale: "了解自己的模式才能真正改變行為。",
      },
    ],
  ],
  [
    "寫感謝信",
    [
      {
        id: "tag-寫感謝信-beginner",
        categoryId: "social",
        level: "beginner",
        title: "寫一則感謝訊息",
        description: "想一位最近幫助過你的人，傳一則具體的感謝訊息給對方。",
        duration: "約 10 分鐘",
        tip: "具體說明對方做了什麼、對你有什麼影響，比單純說謝謝更有力。",
        rationale: "表達感謝能同時提升自己和對方的幸福感。",
      },
      {
        id: "tag-寫感謝信-intermediate",
        categoryId: "social",
        level: "intermediate",
        title: "手寫一封感謝卡",
        description: "用紙筆寫一封感謝卡，寄給或親手交給你想感謝的人。",
        duration: "約 20 分鐘",
        tip: "手寫的溫度是電子訊息無法取代的。",
        rationale: "實體的感謝卡會被珍藏，也讓感謝更有重量。",
      },
      {
        id: "tag-寫感謝信-advanced",
        categoryId: "social",
        level: "advanced",
        title: "建立每日感恩紀錄",
        description: "每天睡前寫下 3 件你感謝的事，持續一週。",
        duration: "約 10 分鐘",
        tip: "越具體越好，「感謝同事幫我改簡報」比「感謝同事」更有感。",
        rationale: "持續的感恩練習能顯著提升生活滿意度。",
      },
    ],
  ],
  [
    "主動關心家人",
    [
      {
        id: "tag-主動關心家人-beginner",
        categoryId: "social",
        level: "beginner",
        title: "打一通電話給家人",
        description: "打電話給一位家人，聊聊他們最近的生活，專心聽 10 分鐘。",
        duration: "約 10 分鐘",
        tip: "問具體的問題，例如「今天吃什麼？」比「最近好嗎？」更容易聊開。",
        rationale: "一通電話能讓家人感受到你的關心。",
      },
      {
        id: "tag-主動關心家人-intermediate",
        categoryId: "social",
        level: "intermediate",
        title: "為家人做一件小事",
        description: "幫家人跑一個腿、做一頓飯、或處理一件他們提過的事。",
        duration: "約 30 分鐘",
        tip: "不用等特殊節日，日常的小舉動更有溫度。",
        rationale: "行動比言語更能表達關心。",
      },
      {
        id: "tag-主動關心家人-advanced",
        categoryId: "social",
        level: "advanced",
        title: "安排一次家庭活動",
        description: "規劃一次全家人一起的活動，例如聚餐、散步或看電影。",
        duration: "約 2 小時",
        tip: "選大家都方便的時間，活動簡單就好。",
        rationale: "共同的回憶是家庭關係最好的黏著劑。",
      },
    ],
  ],
  [
    "參加志工服務",
    [
      {
        id: "tag-參加志工服務-beginner",
        categoryId: "social",
        level: "beginner",
        title: "搜尋志工機會",
        description: "花 15 分鐘搜尋你所在地區的志工服務機會，找到一個感興趣的。",
        duration: "約 15 分鐘",
        tip: "可以搜尋「志工銀行」或當地社福機構的網站。",
        rationale: "先了解有哪些機會，找到適合自己的才能持續。",
      },
      {
        id: "tag-參加志工服務-intermediate",
        categoryId: "social",
        level: "intermediate",
        title: "報名一次志工活動",
        description: "選一個你感興趣的志工活動，完成報名並參加。",
        duration: "約 2-3 小時",
        tip: "第一次選半天的活動就好，先體驗看看。",
        rationale: "實際參與才知道自己喜不喜歡、適不適合。",
      },
      {
        id: "tag-參加志工服務-advanced",
        categoryId: "social",
        level: "advanced",
        title: "成為固定志工",
        description: "選一個你喜歡的組織，承諾每月固定參加一次志工服務。",
        duration: "約 3-4 小時",
        tip: "跟組織溝通你的時間限制，找到雙方都舒服的頻率。",
        rationale: "持續的付出能建立更深的連結和影響力。",
      },
    ],
  ],

  // ─── health ───
  [
    "每日走一萬步",
    [
      {
        id: "tag-每日走一萬步-beginner",
        categoryId: "health",
        level: "beginner",
        title: "午餐後散步 15 分鐘",
        description: "吃完午餐後到附近走一圈，大約 1500-2000 步。",
        duration: "約 15 分鐘",
        tip: "用手機計步器記錄，看到數字會更有動力。",
        rationale: "綁定在午餐後，不用額外找時間就能養成習慣。",
      },
      {
        id: "tag-每日走一萬步-intermediate",
        categoryId: "health",
        level: "intermediate",
        title: "提早一站下車走路",
        description: "通勤時提早一站下車，用走路完成最後一段路程。",
        duration: "約 20 分鐘",
        tip: "帶上耳機聽 Podcast，走路時間變成學習時間。",
        rationale: "融入日常通勤，不增加額外時間負擔。",
      },
      {
        id: "tag-每日走一萬步-advanced",
        categoryId: "health",
        level: "advanced",
        title: "完成一萬步挑戰",
        description: "規劃今天的行走路線，累積完成一萬步並截圖記錄。",
        duration: "約 60-90 分鐘",
        tip: "分散在全天完成：早上 3000、中午 3000、晚上 4000。",
        rationale: "達成目標的截圖會成為你持續的動力。",
      },
    ],
  ],
  [
    "學習冥想",
    [
      {
        id: "tag-學習冥想-beginner",
        categoryId: "health",
        level: "beginner",
        title: "做 5 分鐘呼吸練習",
        description: "找一個安靜的地方坐下，閉眼專注在呼吸上 5 分鐘。",
        duration: "約 5 分鐘",
        tip: "思緒跑掉是正常的，注意到了就輕輕拉回來。",
        rationale: "5 分鐘就足以讓大腦放鬆，感受冥想的效果。",
      },
      {
        id: "tag-學習冥想-intermediate",
        categoryId: "health",
        level: "intermediate",
        title: "跟著引導冥想練習",
        description: "使用冥想 App（如 Headspace、Insight Timer），完成一次 10 分鐘引導冥想。",
        duration: "約 10 分鐘",
        tip: "引導冥想適合初學者，不用擔心自己做得對不對。",
        rationale: "有引導的練習能幫助你更快掌握技巧。",
      },
      {
        id: "tag-學習冥想-advanced",
        categoryId: "health",
        level: "advanced",
        title: "建立每日冥想習慣",
        description: "在每天固定時間（如起床後）進行 15 分鐘的冥想練習。",
        duration: "約 15 分鐘",
        tip: "固定時間比固定長度更重要，讓它變成作息的一部分。",
        rationale: "持續的冥想練習對壓力管理和專注力有顯著效果。",
      },
    ],
  ],
  [
    "減少含糖飲料",
    [
      {
        id: "tag-減少含糖飲料-beginner",
        categoryId: "health",
        level: "beginner",
        title: "記錄今天的飲料攝取",
        description: "記下今天喝的每一杯飲料和含糖量，了解自己的飲料習慣。",
        duration: "約 5 分鐘",
        tip: "手搖飲全糖約 50g 糖，半糖約 25g，WHO 建議每日不超過 25g。",
        rationale: "知道現狀才能設定合理的減糖目標。",
      },
      {
        id: "tag-減少含糖飲料-intermediate",
        categoryId: "health",
        level: "intermediate",
        title: "用替代飲品取代一杯含糖飲料",
        description: "今天把其中一杯含糖飲料換成無糖茶、氣泡水或黑咖啡。",
        duration: "約 5 分鐘",
        tip: "不用一次全戒，一杯一杯慢慢減。",
        rationale: "漸進式的改變比突然戒斷更容易持續。",
      },
      {
        id: "tag-減少含糖飲料-advanced",
        categoryId: "health",
        level: "advanced",
        title: "挑戰三天無糖飲料",
        description: "連續三天只喝水、無糖茶或黑咖啡，記錄身體的變化。",
        duration: "每天 5 分鐘記錄",
        tip: "如果很想喝甜的，試試加檸檬片或薄荷葉的水。",
        rationale: "三天的體驗能讓你感受到減糖對精神和體力的正面影響。",
      },
    ],
  ],
  [
    "早睡早起",
    [
      {
        id: "tag-早睡早起-beginner",
        categoryId: "health",
        level: "beginner",
        title: "設定睡前提醒",
        description: "在手機設定一個睡前 30 分鐘的提醒，開始準備就寢。",
        duration: "約 5 分鐘",
        tip: "提醒響起後就開始收拾、刷牙，不要再滑手機。",
        rationale: "有提醒才不會不知不覺熬夜。",
      },
      {
        id: "tag-早睡早起-intermediate",
        categoryId: "health",
        level: "intermediate",
        title: "建立睡前儀式",
        description: "設計一套 15 分鐘的睡前儀式（如洗澡、伸展、閱讀），每天固定執行。",
        duration: "約 15 分鐘",
        tip: "避免在床上用手機，藍光會影響睡眠品質。",
        rationale: "固定的睡前儀式能幫助大腦進入睡眠模式。",
      },
      {
        id: "tag-早睡早起-advanced",
        categoryId: "health",
        level: "advanced",
        title: "執行 7 天早起計畫",
        description: "連續 7 天在目標時間起床，記錄每天的睡眠時間和起床感受。",
        duration: "每天 5 分鐘記錄",
        tip: "把鬧鐘放在需要起身才能關的地方。",
        rationale: "7 天的紀錄能幫你找到最適合自己的作息。",
      },
    ],
  ],
  [
    "每週運動三次",
    [
      {
        id: "tag-每週運動三次-beginner",
        categoryId: "health",
        level: "beginner",
        title: "做 10 分鐘簡單運動",
        description: "跟著一支短影片做 10 分鐘的居家運動，不需要器材。",
        duration: "約 10 分鐘",
        tip: "YouTube 搜尋「10 分鐘居家運動」就有很多選擇。",
        rationale: "10 分鐘的門檻夠低，讓你願意開始。",
      },
      {
        id: "tag-每週運動三次-intermediate",
        categoryId: "health",
        level: "intermediate",
        title: "完成 30 分鐘有氧運動",
        description: "選一種你喜歡的有氧運動（跑步、游泳、跳繩），完成 30 分鐘。",
        duration: "約 30 分鐘",
        tip: "找一個運動夥伴，互相督促更容易堅持。",
        rationale: "30 分鐘有氧能顯著提升心肺功能和精神狀態。",
      },
      {
        id: "tag-每週運動三次-advanced",
        categoryId: "health",
        level: "advanced",
        title: "制定本週運動計畫",
        description: "規劃本週三次運動的時間、地點和內容，寫進行事曆。",
        duration: "約 15 分鐘",
        tip: "排進行事曆的事情才會真的執行。",
        rationale: "有計畫的運動比隨心情決定更容易持續。",
      },
    ],
  ],
  [
    "學習健康料理",
    [
      {
        id: "tag-學習健康料理-beginner",
        categoryId: "health",
        level: "beginner",
        title: "學做一道簡單沙拉",
        description: "用當季蔬果做一道營養均衡的沙拉，練習基本的食材處理。",
        duration: "約 15 分鐘",
        tip: "橄欖油 + 檸檬汁 + 鹽就是最簡單好吃的沙拉醬。",
        rationale: "沙拉是最適合入門的健康料理。",
      },
      {
        id: "tag-學習健康料理-intermediate",
        categoryId: "health",
        level: "intermediate",
        title: "做一餐均衡的健康餐",
        description: "準備一餐包含蛋白質、蔬菜和全穀物的健康餐點。",
        duration: "約 30 分鐘",
        tip: "雞胸肉 + 蔬菜 + 糙米飯是經典的健康組合。",
        rationale: "學會搭配營養素，每天都能吃得健康。",
      },
      {
        id: "tag-學習健康料理-advanced",
        categoryId: "health",
        level: "advanced",
        title: "備餐三天的健康餐",
        description: "一次準備三天份的健康餐，分裝保存。",
        duration: "約 60 分鐘",
        tip: "選能冷藏保存的食材，避免容易變質的葉菜類。",
        rationale: "批量備餐省時又能確保每天都吃得健康。",
      },
    ],
  ],
  [
    "培養伸展習慣",
    [
      {
        id: "tag-培養伸展習慣-beginner",
        categoryId: "health",
        level: "beginner",
        title: "做 5 分鐘全身伸展",
        description: "起床後做一套簡單的全身伸展：脖子、肩膀、腰部、腿部。",
        duration: "約 5 分鐘",
        tip: "每個動作停留 15-30 秒，不要彈震式拉伸。",
        rationale: "綁定在起床後，不用額外找時間。",
      },
      {
        id: "tag-培養伸展習慣-intermediate",
        categoryId: "health",
        level: "intermediate",
        title: "跟著影片做 15 分鐘瑜伽",
        description: "找一支適合初學者的瑜伽影片，完成 15 分鐘的練習。",
        duration: "約 15 分鐘",
        tip: "不用勉強做到跟影片一樣，量力而為。",
        rationale: "瑜伽結合伸展和呼吸，效果更全面。",
      },
      {
        id: "tag-培養伸展習慣-advanced",
        categoryId: "health",
        level: "advanced",
        title: "設計個人伸展流程",
        description: "根據你身體最緊繃的部位，設計一套專屬的伸展流程並每日執行。",
        duration: "約 20 分鐘",
        tip: "久坐族重點伸展髖屈肌、胸大肌和頸部。",
        rationale: "針對性的伸展比通用流程更有效。",
      },
    ],
  ],

  // ─── academic ───
  [
    "每日閱讀 30 分鐘",
    [
      {
        id: "tag-每日閱讀30分鐘-beginner",
        categoryId: "academic",
        level: "beginner",
        title: "閱讀 10 分鐘",
        description: "選一本你感興趣的書，專注閱讀 10 分鐘，不看手機。",
        duration: "約 10 分鐘",
        tip: "設定計時器，時間到就可以停。先養成習慣再增加時間。",
        rationale: "10 分鐘的門檻夠低，讓你每天都願意打開書。",
      },
      {
        id: "tag-每日閱讀30分鐘-intermediate",
        categoryId: "academic",
        level: "intermediate",
        title: "閱讀並做簡單筆記",
        description: "閱讀 20 分鐘後，花 5 分鐘寫下一個你印象最深的重點。",
        duration: "約 25 分鐘",
        tip: "筆記不用多，一句話就好。",
        rationale: "做筆記能將閱讀從「看過」變成「記住」。",
      },
      {
        id: "tag-每日閱讀30分鐘-advanced",
        categoryId: "academic",
        level: "advanced",
        title: "完成 30 分鐘深度閱讀",
        description: "在安靜的環境中專注閱讀 30 分鐘，結束後寫下三個收穫。",
        duration: "約 35 分鐘",
        tip: "找一個固定的閱讀時段，例如睡前或通勤時。",
        rationale: "持續 30 分鐘的閱讀能進入心流狀態，吸收更深。",
      },
    ],
  ],
  [
    "學習新語言",
    [
      {
        id: "tag-學習新語言-beginner",
        categoryId: "academic",
        level: "beginner",
        title: "學 5 個新單字",
        description: "用語言學習 App 或單字卡，學習並複誦 5 個新單字。",
        duration: "約 10 分鐘",
        tip: "搭配例句一起記，比單背單字有效。",
        rationale: "每天 5 個，一個月就有 150 個新單字。",
      },
      {
        id: "tag-學習新語言-intermediate",
        categoryId: "academic",
        level: "intermediate",
        title: "聽 10 分鐘目標語言",
        description: "聽一段目標語言的 Podcast 或影片，試著抓出你聽懂的單字。",
        duration: "約 15 分鐘",
        tip: "不用全聽懂，能抓到幾個字就是進步。",
        rationale: "大量聽力輸入是語言習得最自然的方式。",
      },
      {
        id: "tag-學習新語言-advanced",
        categoryId: "academic",
        level: "advanced",
        title: "用目標語言寫一段話",
        description: "用你正在學的語言寫 5 句關於今天生活的句子。",
        duration: "約 20 分鐘",
        tip: "不用怕犯錯，能表達意思就算成功。",
        rationale: "輸出練習是鞏固語言能力最有效的方式。",
      },
    ],
  ],
  [
    "完成線上課程",
    [
      {
        id: "tag-完成線上課程-beginner",
        categoryId: "academic",
        level: "beginner",
        title: "看完一堂課程影片",
        description: "打開你正在上的線上課程，看完一個章節的影片。",
        duration: "約 15 分鐘",
        tip: "不用做筆記，先看完就好。",
        rationale: "「先完成再完美」，看完比寫出完美筆記更重要。",
      },
      {
        id: "tag-完成線上課程-intermediate",
        categoryId: "academic",
        level: "intermediate",
        title: "完成一章並做重點筆記",
        description: "看完一個章節後，用自己的話寫下 3 個最重要的觀念。",
        duration: "約 30 分鐘",
        tip: "用自己的話寫，而非抄講師的原話。",
        rationale: "用自己的話重述能確認你真的理解了。",
      },
      {
        id: "tag-完成線上課程-advanced",
        categoryId: "academic",
        level: "advanced",
        title: "完成課程作業或實作",
        description: "完成當前章節的練習題或動手做一個課程中的實作專案。",
        duration: "約 45 分鐘",
        tip: "卡關時先自己想 10 分鐘，再看解答。",
        rationale: "動手實作是將知識轉化為技能的關鍵。",
      },
    ],
  ],
  [
    "做讀書筆記",
    [
      {
        id: "tag-做讀書筆記-beginner",
        categoryId: "academic",
        level: "beginner",
        title: "寫下一個閱讀心得",
        description: "回想最近讀過的內容，用 3 句話寫下你最大的收穫。",
        duration: "約 10 分鐘",
        tip: "問自己：這段內容改變了我什麼想法？",
        rationale: "簡短的心得就能強化記憶。",
      },
      {
        id: "tag-做讀書筆記-intermediate",
        categoryId: "academic",
        level: "intermediate",
        title: "做一頁視覺筆記",
        description: "用圖文並茂的方式，在一頁紙上整理一個章節的重點。",
        duration: "約 25 分鐘",
        tip: "用箭頭、框框和簡單的圖示讓筆記更直覺。",
        rationale: "視覺化筆記能幫助建立知識間的連結。",
      },
      {
        id: "tag-做讀書筆記-advanced",
        categoryId: "academic",
        level: "advanced",
        title: "寫一篇讀書摘要",
        description: "選一本最近讀完的書，寫一篇 300 字的摘要，包含核心觀點和個人見解。",
        duration: "約 40 分鐘",
        tip: "先列出 3-5 個核心觀點，再圍繞它們展開。",
        rationale: "能寫出摘要代表你真正消化了書的內容。",
      },
    ],
  ],
  [
    "準備證照考試",
    [
      {
        id: "tag-準備證照考試-beginner",
        categoryId: "academic",
        level: "beginner",
        title: "了解考試資訊",
        description: "花 15 分鐘查詢目標證照的考試科目、時間、費用和報名方式。",
        duration: "約 15 分鐘",
        tip: "把重要日期記進行事曆，避免錯過報名。",
        rationale: "清楚考試全貌才能制定有效的備考計畫。",
      },
      {
        id: "tag-準備證照考試-intermediate",
        categoryId: "academic",
        level: "intermediate",
        title: "完成一回模擬考題",
        description: "找到歷年考古題或模擬題，完成一個科目的練習。",
        duration: "約 30 分鐘",
        tip: "計時作答，模擬考試的時間壓力。",
        rationale: "做題目能快速找出自己的弱點。",
      },
      {
        id: "tag-準備證照考試-advanced",
        categoryId: "academic",
        level: "advanced",
        title: "制定每週讀書計畫",
        description: "根據考試日期倒推，為每週安排具體的複習進度和目標。",
        duration: "約 30 分鐘",
        tip: "預留每週一天做複習和模擬考。",
        rationale: "有計畫的備考比隨意唸書效率高數倍。",
      },
    ],
  ],
  [
    "學習程式設計",
    [
      {
        id: "tag-學習程式設計-beginner",
        categoryId: "academic",
        level: "beginner",
        title: "完成一個程式教學",
        description: "在 Codecademy 或 freeCodeCamp 上完成一堂入門課程。",
        duration: "約 20 分鐘",
        tip: "邊看邊動手打，不要只是看不練。",
        rationale: "互動式教學是程式入門最友善的方式。",
      },
      {
        id: "tag-學習程式設計-intermediate",
        categoryId: "academic",
        level: "intermediate",
        title: "解一道程式練習題",
        description: "在 LeetCode Easy 或 Codewars 上解一道簡單的程式題。",
        duration: "約 30 分鐘",
        tip: "先想解法再寫程式，想不出來就看提示。",
        rationale: "解題能訓練邏輯思考和程式實作能力。",
      },
      {
        id: "tag-學習程式設計-advanced",
        categoryId: "academic",
        level: "advanced",
        title: "做一個小專案",
        description: "用你學到的技術做一個簡單的小工具（如計算機、待辦清單）。",
        duration: "約 60 分鐘",
        tip: "功能越簡單越好，先做出來再慢慢加功能。",
        rationale: "動手做專案是把知識轉化為實力的最快方式。",
      },
    ],
  ],
  [
    "研究一個新主題",
    [
      {
        id: "tag-研究一個新主題-beginner",
        categoryId: "academic",
        level: "beginner",
        title: "花 15 分鐘初步搜索",
        description: "選一個你好奇的主題，花 15 分鐘閱讀相關的入門介紹文章。",
        duration: "約 15 分鐘",
        tip: "維基百科是了解一個主題全貌的好起點。",
        rationale: "先建立大框架，再深入細節會更有效率。",
      },
      {
        id: "tag-研究一個新主題-intermediate",
        categoryId: "academic",
        level: "intermediate",
        title: "整理研究筆記",
        description: "將你搜索到的資訊整理成筆記，列出核心概念和待深入的問題。",
        duration: "約 25 分鐘",
        tip: "用問題引導研究：「這個主題最重要的 3 件事是什麼？」",
        rationale: "整理筆記能幫助你消化資訊並發現知識缺口。",
      },
      {
        id: "tag-研究一個新主題-advanced",
        categoryId: "academic",
        level: "advanced",
        title: "寫一篇簡短的研究心得",
        description: "根據你的研究，寫一篇 300 字的心得，包含你學到什麼和你的看法。",
        duration: "約 40 分鐘",
        tip: "想像你在向朋友解釋這個主題。",
        rationale: "能向別人解釋清楚，代表你真的理解了。",
      },
    ],
  ],

  // ─── work ───
  [
    "學習時間管理",
    [
      {
        id: "tag-學習時間管理-beginner",
        categoryId: "work",
        level: "beginner",
        title: "記錄今天的時間分配",
        description: "每隔一小時記錄你在做什麼，到晚上整理出完整的時間日誌。",
        duration: "每次 1 分鐘，共約 10 分鐘",
        tip: "不用改變任何行為，先如實記錄就好。",
        rationale: "知道時間花在哪裡，才能開始管理它。",
      },
      {
        id: "tag-學習時間管理-intermediate",
        categoryId: "work",
        level: "intermediate",
        title: "嘗試一次番茄鐘工作法",
        description: "設定 25 分鐘專注工作 + 5 分鐘休息，完成 2 輪番茄鐘。",
        duration: "約 60 分鐘",
        tip: "專注時間內關閉通知，手機翻面朝下。",
        rationale: "番茄鐘是最容易上手的時間管理工具。",
      },
      {
        id: "tag-學習時間管理-advanced",
        categoryId: "work",
        level: "advanced",
        title: "用艾森豪矩陣規劃一天",
        description: "列出今天所有待辦事項，用「重要/緊急」四象限分類並排序。",
        duration: "約 20 分鐘",
        tip: "大部分人花太多時間在「緊急但不重要」的事上。",
        rationale: "優先處理「重要但不緊急」的事，才能減少危機。",
      },
    ],
  ],
  [
    "建立個人品牌",
    [
      {
        id: "tag-建立個人品牌-beginner",
        categoryId: "work",
        level: "beginner",
        title: "更新你的專業簡介",
        description: "花 15 分鐘更新 LinkedIn 或個人網站的自我介紹和照片。",
        duration: "約 15 分鐘",
        tip: "用一句話說明你能提供什麼價值，而非只列頭銜。",
        rationale: "專業簡介是別人認識你的第一印象。",
      },
      {
        id: "tag-建立個人品牌-intermediate",
        categoryId: "work",
        level: "intermediate",
        title: "寫一篇專業分享文",
        description: "分享一個你在工作中學到的經驗或觀點，發佈在專業平台上。",
        duration: "約 30 分鐘",
        tip: "不用寫長文，300 字的實用心得就很有價值。",
        rationale: "持續的知識分享能建立你的專業形象。",
      },
      {
        id: "tag-建立個人品牌-advanced",
        categoryId: "work",
        level: "advanced",
        title: "規劃你的內容策略",
        description: "決定你想在哪個領域被認識，規劃未來一個月的 4 篇分享主題。",
        duration: "約 40 分鐘",
        tip: "選一個你有獨特見解的小眾領域，比大眾話題更容易脫穎而出。",
        rationale: "有策略的內容經營比隨機發文效果好十倍。",
      },
    ],
  ],
  [
    "學習簡報技巧",
    [
      {
        id: "tag-學習簡報技巧-beginner",
        categoryId: "work",
        level: "beginner",
        title: "觀摩一場優秀簡報",
        description: "在 TED 上看一場演講，記下 3 個你覺得講者做得好的技巧。",
        duration: "約 20 分鐘",
        tip: "注意講者的開場方式、肢體語言和如何使用投影片。",
        rationale: "觀摩好的範例是學習簡報最快的方式。",
      },
      {
        id: "tag-學習簡報技巧-intermediate",
        categoryId: "work",
        level: "intermediate",
        title: "優化一份現有簡報",
        description: "拿出你最近做的一份簡報，用「一頁一重點」原則重新整理。",
        duration: "約 30 分鐘",
        tip: "刪掉多餘的文字，每頁只保留一個核心訊息。",
        rationale: "簡潔的簡報比塞滿文字的更有說服力。",
      },
      {
        id: "tag-學習簡報技巧-advanced",
        categoryId: "work",
        level: "advanced",
        title: "練習一次 5 分鐘簡報",
        description: "準備一個 5 分鐘的簡報，對著鏡子或錄影練習一次。",
        duration: "約 30 分鐘",
        tip: "看回放會發現很多自己沒注意到的習慣動作。",
        rationale: "實際演練是提升簡報能力最有效的方式。",
      },
    ],
  ],
  [
    "精進專業技能",
    [
      {
        id: "tag-精進專業技能-beginner",
        categoryId: "work",
        level: "beginner",
        title: "閱讀一篇專業領域文章",
        description: "花 15 分鐘閱讀你專業領域的最新文章或產業報告。",
        duration: "約 15 分鐘",
        tip: "訂閱 2-3 個產業電子報，讓資訊主動送到你面前。",
        rationale: "保持對產業動態的了解是專業成長的基礎。",
      },
      {
        id: "tag-精進專業技能-intermediate",
        categoryId: "work",
        level: "intermediate",
        title: "學習一個新工具或方法",
        description: "花 30 分鐘學習一個你工作中用得到但還不熟的工具或方法。",
        duration: "約 30 分鐘",
        tip: "學完立刻在工作中試用一次，才能真正記住。",
        rationale: "每週學一個新技巧，一年就多了 52 項能力。",
      },
      {
        id: "tag-精進專業技能-advanced",
        categoryId: "work",
        level: "advanced",
        title: "完成一個學習專案",
        description: "選一個你想精進的技能，做一個小型的練習專案來實際應用。",
        duration: "約 60 分鐘",
        tip: "找一個真實的工作問題來練習，學以致用效果最好。",
        rationale: "做中學是精進專業技能最有效的方式。",
      },
    ],
  ],
  [
    "建立人脈網絡",
    [
      {
        id: "tag-建立人脈網絡-beginner",
        categoryId: "work",
        level: "beginner",
        title: "聯繫一位專業人脈",
        description: "在 LinkedIn 或通訊軟體上，向一位你欣賞的專業人士發一則訊息。",
        duration: "約 10 分鐘",
        tip: "提到你們的共同點或你欣賞對方的具體原因。",
        rationale: "主動出擊是建立人脈的第一步。",
      },
      {
        id: "tag-建立人脈網絡-intermediate",
        categoryId: "work",
        level: "intermediate",
        title: "參加一場專業活動",
        description: "報名並參加一場線上或線下的產業活動、講座或工作坊。",
        duration: "約 2 小時",
        tip: "準備一個 30 秒的自我介紹和 2-3 個問題。",
        rationale: "在專業場合認識的人脈最有可能帶來合作機會。",
      },
      {
        id: "tag-建立人脈網絡-advanced",
        categoryId: "work",
        level: "advanced",
        title: "約一位業界前輩咖啡聊天",
        description: "邀約一位你想學習的前輩，進行 30 分鐘的職涯諮詢對話。",
        duration: "約 45 分鐘",
        tip: "事先準備好 3 個具體問題，珍惜對方的時間。",
        rationale: "一次深度對話的價值遠超過十場社交聚會。",
      },
    ],
  ],
  [
    "學會任務排序",
    [
      {
        id: "tag-學會任務排序-beginner",
        categoryId: "work",
        level: "beginner",
        title: "列出今天的三大優先事項",
        description: "在開始工作前，從所有待辦中挑出最重要的 3 件事。",
        duration: "約 5 分鐘",
        tip: "問自己：「如果今天只能做 3 件事，會選哪些？」",
        rationale: "明確優先順序能避免在小事上浪費時間。",
      },
      {
        id: "tag-學會任務排序-intermediate",
        categoryId: "work",
        level: "intermediate",
        title: "用 RICE 模型排序任務",
        description: "列出你的待辦清單，用影響力（Impact）和努力程度（Effort）為每項評分並排序。",
        duration: "約 20 分鐘",
        tip: "優先做「高影響力 + 低努力」的任務。",
        rationale: "用框架排序比憑感覺更客觀有效。",
      },
      {
        id: "tag-學會任務排序-advanced",
        categoryId: "work",
        level: "advanced",
        title: "建立每週任務檢視流程",
        description: "每週五花 20 分鐘回顧本週完成事項，規劃下週的優先任務。",
        duration: "約 20 分鐘",
        tip: "記錄哪些任務被拖延了，分析原因。",
        rationale: "定期檢視能持續優化你的任務管理系統。",
      },
    ],
  ],
  [
    "提升溝通能力",
    [
      {
        id: "tag-提升溝通能力-beginner",
        categoryId: "work",
        level: "beginner",
        title: "練習結論先行",
        description: "在今天的一次溝通中（訊息或口頭），先說結論再說原因。",
        duration: "約 5 分鐘",
        tip: "用「我的建議是 __，因為 __」的句型。",
        rationale: "結論先行能讓對方更快理解你的意思。",
      },
      {
        id: "tag-提升溝通能力-intermediate",
        categoryId: "work",
        level: "intermediate",
        title: "改寫一封重要的 Email",
        description: "拿出一封你要發送的 Email，用「簡潔、清晰、有行動項目」的原則重新修改。",
        duration: "約 15 分鐘",
        tip: "每封 Email 都要有明確的下一步行動。",
        rationale: "好的書面溝通能減少來回確認的時間。",
      },
      {
        id: "tag-提升溝通能力-advanced",
        categoryId: "work",
        level: "advanced",
        title: "練習一次困難對話",
        description: "針對一個你需要進行的困難對話，寫下你要表達的重點並演練一次。",
        duration: "約 30 分鐘",
        tip: "用「我觀察到 __，我的感受是 __，我希望 __」的非暴力溝通框架。",
        rationale: "事前準備能大幅降低困難對話的焦慮。",
      },
    ],
  ],

  // ─── finance ───
  [
    "記帳習慣",
    [
      {
        id: "tag-記帳習慣-beginner",
        categoryId: "finance",
        level: "beginner",
        title: "記錄今天的所有花費",
        description: "在睡前花 5 分鐘，把今天的每一筆消費記錄下來。",
        duration: "約 5 分鐘",
        tip: "用手機記帳 App 最方便，花完就記。",
        rationale: "知道錢花在哪裡，是理財的第一步。",
      },
      {
        id: "tag-記帳習慣-intermediate",
        categoryId: "finance",
        level: "intermediate",
        title: "分類整理本週消費",
        description: "將這週的消費分類（食、衣、住、行、娛樂），算出各類比例。",
        duration: "約 15 分鐘",
        tip: "大部分人會驚訝飲食和娛樂佔的比例。",
        rationale: "看到比例才能知道哪裡可以調整。",
      },
      {
        id: "tag-記帳習慣-advanced",
        categoryId: "finance",
        level: "advanced",
        title: "設定分類預算上限",
        description: "根據分析結果，為每個消費類別設定月度預算上限。",
        duration: "約 20 分鐘",
        tip: "先從最容易超支的類別開始控制。",
        rationale: "有預算限制才能真正控制支出。",
      },
    ],
  ],
  [
    "學習投資基礎",
    [
      {
        id: "tag-學習投資基礎-beginner",
        categoryId: "finance",
        level: "beginner",
        title: "了解投資基本概念",
        description: "花 15 分鐘閱讀一篇關於股票、基金或 ETF 的入門介紹。",
        duration: "約 15 分鐘",
        tip: "先了解什麼是 ETF，它是最適合新手的投資工具之一。",
        rationale: "基礎觀念穩固，才不會被市場雜訊帶著走。",
      },
      {
        id: "tag-學習投資基礎-intermediate",
        categoryId: "finance",
        level: "intermediate",
        title: "模擬投資練習",
        description: "用虛擬投資 App 或紙上模擬，練習買賣一支股票或 ETF。",
        duration: "約 20 分鐘",
        tip: "先用模擬帳戶練手感，不要急著用真金白銀。",
        rationale: "模擬投資能在零風險下學習市場運作。",
      },
      {
        id: "tag-學習投資基礎-advanced",
        categoryId: "finance",
        level: "advanced",
        title: "制定你的投資計畫",
        description: "根據你的風險承受度和目標，寫下你的投資策略和每月投入金額。",
        duration: "約 30 分鐘",
        tip: "定期定額是最適合新手的策略，避免追高殺低。",
        rationale: "有計畫的投資比衝動下單更穩健。",
      },
    ],
  ],
  [
    "減少不必要開支",
    [
      {
        id: "tag-減少不必要開支-beginner",
        categoryId: "finance",
        level: "beginner",
        title: "找出一筆可省的訂閱",
        description: "檢查你的信用卡帳單或 App Store，找出一個你不常用的訂閱服務。",
        duration: "約 10 分鐘",
        tip: "很多人忘了自己訂了哪些服務，定期檢查很重要。",
        rationale: "取消一個月 100 元的訂閱，一年就省 1200 元。",
      },
      {
        id: "tag-減少不必要開支-intermediate",
        categoryId: "finance",
        level: "intermediate",
        title: "實行 24 小時消費冷靜期",
        description: "今天如果想買非必需品，先等 24 小時再決定是否購買。",
        duration: "約 5 分鐘",
        tip: "把想買的東西加入購物車但不結帳，明天再看還想不想買。",
        rationale: "衝動消費是不必要開支的最大來源。",
      },
      {
        id: "tag-減少不必要開支-advanced",
        categoryId: "finance",
        level: "advanced",
        title: "做一次消費斷捨離",
        description:
          "列出你每月的固定支出，標記哪些是「需要」、哪些是「想要」，削減 2 項「想要」。",
        duration: "約 30 分鐘",
        tip: "不是要你過苦日子，而是把錢花在真正讓你開心的事上。",
        rationale: "有意識的消費比無意識的節省更有效。",
      },
    ],
  ],
  [
    "設定儲蓄目標",
    [
      {
        id: "tag-設定儲蓄目標-beginner",
        categoryId: "finance",
        level: "beginner",
        title: "算出你的月存款能力",
        description: "用收入減去固定支出，算出你每月能存多少錢。",
        duration: "約 10 分鐘",
        tip: "存不到收入的 10% 也沒關係，先從 5% 開始。",
        rationale: "知道能存多少才能設定合理的目標。",
      },
      {
        id: "tag-設定儲蓄目標-intermediate",
        categoryId: "finance",
        level: "intermediate",
        title: "設定一個具體的儲蓄目標",
        description: "選一個你想存錢達成的目標（旅行、3C、緊急預備金），算出需要的金額和時間。",
        duration: "約 15 分鐘",
        tip: "把目標寫在看得到的地方，視覺化提醒很有效。",
        rationale: "有具體目標比「盡量存」更有動力。",
      },
      {
        id: "tag-設定儲蓄目標-advanced",
        categoryId: "finance",
        level: "advanced",
        title: "設定自動轉帳儲蓄",
        description: "在銀行設定每月發薪日自動轉帳到儲蓄帳戶。",
        duration: "約 15 分鐘",
        tip: "「先存再花」比「花完再存」有效百倍。",
        rationale: "自動化儲蓄是最不需要意志力的理財方式。",
      },
    ],
  ],
  [
    "了解理財工具",
    [
      {
        id: "tag-了解理財工具-beginner",
        categoryId: "finance",
        level: "beginner",
        title: "認識三種基本理財工具",
        description: "花 15 分鐘了解定存、基金、ETF 這三種理財工具的差異和特性。",
        duration: "約 15 分鐘",
        tip: "風險和報酬成正比，先了解風險再決定。",
        rationale: "了解工具才能選出適合自己的理財方式。",
      },
      {
        id: "tag-了解理財工具-intermediate",
        categoryId: "finance",
        level: "intermediate",
        title: "比較不同理財帳戶",
        description: "比較 2-3 家銀行或券商的手續費、利率和功能，選出最適合你的。",
        duration: "約 25 分鐘",
        tip: "注意隱藏費用，例如管理費和交易手續費。",
        rationale: "選對平台能省下長期的手續費成本。",
      },
      {
        id: "tag-了解理財工具-advanced",
        categoryId: "finance",
        level: "advanced",
        title: "開立一個投資帳戶",
        description: "選定一家券商，完成開戶流程並存入第一筆小額資金。",
        duration: "約 30 分鐘",
        tip: "先投入你完全可以承受損失的金額，例如 3000 元。",
        rationale: "開戶是從「想投資」到「開始投資」最關鍵的一步。",
      },
    ],
  ],
  [
    "開始存美股",
    [
      {
        id: "tag-開始存美股-beginner",
        categoryId: "finance",
        level: "beginner",
        title: "了解美股基本知識",
        description: "花 15 分鐘了解美股交易時間、常見指數（S&P 500）和如何在台灣買美股。",
        duration: "約 15 分鐘",
        tip: "複委託和海外券商是台灣投資人買美股的兩種主要方式。",
        rationale: "基礎知識是投資美股的第一步。",
      },
      {
        id: "tag-開始存美股-intermediate",
        categoryId: "finance",
        level: "intermediate",
        title: "研究一支美股 ETF",
        description: "選一支知名的美股 ETF（如 VOO 或 VTI），了解它的成分和歷史報酬。",
        duration: "約 20 分鐘",
        tip: "指數型 ETF 適合不想選股的長期投資人。",
        rationale: "深入了解一個標的，比淺嚐十個更有幫助。",
      },
      {
        id: "tag-開始存美股-advanced",
        categoryId: "finance",
        level: "advanced",
        title: "制定美股定期定額計畫",
        description: "決定每月投入金額和標的，設定定期定額或手動買入的時程。",
        duration: "約 20 分鐘",
        tip: "定期定額能平滑買入成本，不用擔心買在高點。",
        rationale: "有計畫的定期投入是累積資產最穩健的方式。",
      },
    ],
  ],
  [
    "建立緊急預備金",
    [
      {
        id: "tag-建立緊急預備金-beginner",
        categoryId: "finance",
        level: "beginner",
        title: "算出你需要的預備金金額",
        description: "計算你 3 個月的基本生活費（房租、伙食、交通、保險），這就是你的目標。",
        duration: "約 10 分鐘",
        tip: "基本生活費不包含娛樂和奢侈品。",
        rationale: "知道目標金額才能開始有計畫地存。",
      },
      {
        id: "tag-建立緊急預備金-intermediate",
        categoryId: "finance",
        level: "intermediate",
        title: "開一個專用儲蓄帳戶",
        description: "在銀行開一個專門存預備金的帳戶，和日常花費帳戶分開。",
        duration: "約 15 分鐘",
        tip: "選一個利率稍高的數位帳戶，讓預備金也能生利息。",
        rationale: "分開帳戶才不會不小心花掉預備金。",
      },
      {
        id: "tag-建立緊急預備金-advanced",
        categoryId: "finance",
        level: "advanced",
        title: "設定每月自動存入預備金",
        description: "設定薪資入帳後自動轉帳固定金額到預備金帳戶。",
        duration: "約 10 分鐘",
        tip: "即使每月只存 2000 元，一年也有 24000 元的安全網。",
        rationale: "自動化存款讓預備金在不知不覺中累積。",
      },
    ],
  ],
]);

/**
 * 根據選擇的 tags 回傳對應的靜態行動。
 * 取第一個有對應資料的 tag，沒有則回傳 null。
 */
export function getTagActions(tags: string[]): IAction[] | null {
  for (const tag of tags) {
    const actions = tagActionsMap.get(tag);
    if (actions) return actions;
  }
  return null;
}
