import {
  BellOutlineSvg,
  BellSolidSvg,
  HomeOutlineSvg,
  HomeSolidSvg,
  MedalOutlineSvg,
  MedalSolidSvg,
  SearchOutlineSvg,
  SearchSolidSvg,
  SettingOutlineSvg,
  SettingSolidSvg,
  UserOutlineSvg,
  UserSolidSvg,
} from "@daodao/assets";

export const menuItems = [
  {
    activeIcon: HomeSolidSvg,
    icon: HomeOutlineSvg,
    label: "主頁",
    href: "/",
    isMatch: (pathname: string) => pathname === "/",
  },
  {
    activeIcon: SearchSolidSvg,
    icon: SearchOutlineSvg,
    label: "探索社群",
    href: "/explore",
    hidden: true,
    isMatch: (pathname: string) => pathname === "/explore",
  },
  {
    activeIcon: MedalSolidSvg,
    icon: MedalOutlineSvg,
    label: "成長地圖",
    href: "/growth-map",
    hidden: true,
    isMatch: (pathname: string) => pathname === "/growth-map",
  },
  {
    activeIcon: BellSolidSvg,
    icon: BellOutlineSvg,
    label: "最新通知",
    href: "/notifications",
    isMatch: (pathname: string) => pathname === "/notifications",
  },
  {
    activeIcon: UserSolidSvg,
    icon: UserOutlineSvg,
    label: "我的小島",
    href: (identifier: string) => `/users/${identifier}`,
    isMatch: (pathname: string, identifier: string) => pathname.startsWith(`/users/${identifier}`),
  },
  {
    activeIcon: SettingSolidSvg,
    icon: SettingOutlineSvg,
    label: "設定",
    href: "/settings",
    isMatch: (pathname: string) => pathname.startsWith("/settings"),
  },
];
