import {
  BellOutlineSvg,
  BellSolidSvg,
  HomeOutlineSvg,
  HomeSolidSvg,
  MedalOutlineSvg,
  MedalSolidSvg,
  SearchOutlineSvg,
  SearchSolidSvg,
  SettingOutlineSvg,
  SettingSolidSvg,
  UserOutlineSvg,
  UserSolidSvg,
} from "@daodao/assets";

export const menuItems = [
  {
    activeIcon: HomeSolidSvg,
    icon: HomeOutlineSvg,
    labelKey: "nav_home",
    href: "/",
    isMatch: (pathname: string) => pathname === "/",
  },
  {
    activeIcon: SearchSolidSvg,
    icon: SearchOutlineSvg,
    labelKey: "nav_explore",
    href: "/explore",
    hidden: true,
    isMatch: (pathname: string) => pathname === "/explore",
  },
  {
    activeIcon: MedalSolidSvg,
    icon: MedalOutlineSvg,
    labelKey: "nav_growth_map",
    href: "/growth-map",
    hidden: true,
    isMatch: (pathname: string) => pathname === "/growth-map",
  },
  {
    activeIcon: BellSolidSvg,
    icon: BellOutlineSvg,
    labelKey: "nav_notifications",
    href: "/notifications",
    isMatch: (pathname: string) => pathname === "/notifications",
  },
  {
    activeIcon: UserSolidSvg,
    icon: UserOutlineSvg,
    labelKey: "nav_my_island",
    href: (identifier: string) => `/users/${identifier}`,
    isMatch: (pathname: string, identifier: string) => pathname.startsWith(`/users/${identifier}`),
  },
  {
    activeIcon: SettingSolidSvg,
    icon: SettingOutlineSvg,
    labelKey: "nav_settings",
    href: "/settings",
    hidden: true,
    isMatch: (pathname: string) => pathname.startsWith("/settings"),
  },
];
