import {
  BellOutlineSvg,
  BellSolidSvg,
  HomeOutlineSvg,
  HomeSolidSvg,
  MedalOutlineSvg,
  MedalSolidSvg,
  SearchOutlineSvg,
  SearchSolidSvg,
  SettingOutlineSvg,
  SettingSolidSvg,
  UserOutlineSvg,
  UserSolidSvg,
} from "@daodao/assets";

export const getMenuItems = (t: (key: string) => string) => [
  {
    activeIcon: HomeSolidSvg,
    icon: HomeOutlineSvg,
    label: t("nav_home"),
    href: "/",
    isMatch: (pathname: string) => pathname === "/",
  },
  {
    activeIcon: SearchSolidSvg,
    icon: SearchOutlineSvg,
    label: t("nav_explore"),
    href: "/explore",
    hidden: true,
    isMatch: (pathname: string) => pathname === "/explore",
  },
  {
    activeIcon: MedalSolidSvg,
    icon: MedalOutlineSvg,
    label: t("nav_growth_map"),
    href: "/growth-map",
    hidden: true,
    isMatch: (pathname: string) => pathname === "/growth-map",
  },
  {
    activeIcon: BellSolidSvg,
    icon: BellOutlineSvg,
    label: t("nav_notifications"),
    href: "/notifications",
    isMatch: (pathname: string) => pathname === "/notifications",
  },
  {
    activeIcon: UserSolidSvg,
    icon: UserOutlineSvg,
    label: t("nav_my_island"),
    href: (identifier: string) => `/users/${identifier}`,
    isMatch: (pathname: string, identifier: string) => pathname.startsWith(`/users/${identifier}`),
  },
  {
    activeIcon: SettingSolidSvg,
    icon: SettingOutlineSvg,
    label: t("nav_settings"),
    href: "/settings",
    isMatch: (pathname: string) => pathname.startsWith("/settings"),
  },
];
