import type { QuarterlyReportData } from "./types";

export const MOCK_REPORT_DATA: QuarterlyReportData = {
  user: { name: "小海", age: 28, transition: "行銷 → UX Design" },
  quarter: { year: 2026, quarter: 2, totalDays: 91 },
  stats: { activeDays: 45, topics: 12, interactions: 156, friends: 18 },
  months: [
    { month: 4, activeDays: 15, topics: 4, highlights: ["完成 UX Bootcamp 結業", "開始 Portfolio 規劃"] },
    { month: 5, activeDays: 18, topics: 5, highlights: ["首件 Portfolio 作品完成", "參加設計工作坊"] },
    { month: 6, activeDays: 12, topics: 3, highlights: ["加入 UX 設計讀書會", "完成訪談練習"] },
  ],
  milestones: [
    { date: "2026-04-12", title: "UX Bootcamp 結業", description: "歷時 6 週，完成所有課程模組與期末專案" },
    { date: "2026-05-20", title: "首件 Portfolio 完成", description: "食物外送 App 重新設計 case study 上線" },
    { date: "2026-06-08", title: "加入 UX 設計讀書會", description: "每週二固定共學，與 8 位設計師交流" },
  ],
  friends: [
    { name: "小立", isCore: true },
    { name: "佳佳", isCore: true },
    { name: "阿明", isCore: true },
    { name: "小琳", isCore: true },
    { name: "志偉", isCore: true },
    { name: "美華", isCore: false },
    { name: "大毛", isCore: false },
    { name: "阿芳", isCore: false },
    { name: "小豪", isCore: false },
    { name: "思穎", isCore: false },
    { name: "家維", isCore: false },
    { name: "品萱", isCore: false },
    { name: "宗翰", isCore: false },
    { name: "雅婷", isCore: false },
    { name: "柏宇", isCore: false },
    { name: "欣怡", isCore: false },
    { name: "建志", isCore: false },
    { name: "淑芬", isCore: false },
  ],
  learningRadar: [
    { dimension: "UX 研究", score: 80 },
    { dimension: "視覺設計", score: 65 },
    { dimension: "原型製作", score: 70 },
    { dimension: "前端基礎", score: 45 },
    { dimension: "訪談", score: 55 },
    { dimension: "設計思考", score: 75 },
  ],
  moodCurve: [
    { week: 1, mood: "frustrated", score: 25 },
    { week: 2, mood: "bored", score: 35 },
    { week: 3, mood: "neutral", score: 50 },
    { week: 4, mood: "neutral", score: 45 },
    { week: 5, mood: "fine", score: 60 },
    { week: 6, mood: "fine", score: 65 },
    { week: 7, mood: "fine", score: 60 },
    { week: 8, mood: "happy", score: 75 },
    { week: 9, mood: "fine", score: 70 },
    { week: 10, mood: "happy", score: 80 },
    { week: 11, mood: "happy", score: 85 },
    { week: 12, mood: "happy", score: 90 },
  ],
  actions: [
    { title: "完成 3 件 Portfolio 作品", description: "延續本季的動力，建立完整作品集" },
    { title: "持續參與 UX 讀書會", description: "深化社群連結，擴大你的群島網絡" },
    { title: "找到一位業界 Mentor", description: "從島友中尋找在職設計師，定期 1:1" },
  ],
};
