export const EDUCATION_STAGE_OPTIONS = [
  { value: "high", label: "高中/職" },
  { value: "associate", label: "專科" },
  { value: "university", label: "大學" },
  { value: "master", label: "碩士" },
  { value: "doctorate", label: "博士" },
  { value: "other", label: "其他" },
] as const;

export const POSITION_OPTIONS = [
  { value: "normal_student", label: "一般學生" },
  { value: "experimental_education_student", label: "實驗教育學生" },
  { value: "experimental_educator", label: "實驗教育工作者" },
  { value: "educator", label: "教育工作者" },
  { value: "parents", label: "家長" },
  { value: "civil_servant", label: "公務員" },
  { value: "military", label: "軍人" },
  { value: "teacher", label: "教師" },
  { value: "police_firefighter", label: "警消人員" },
  { value: "medical_staff", label: "醫護人員" },
  { value: "lawyer", label: "律師" },
  { value: "accountant", label: "會計師" },
  { value: "architect", label: "建築師" },
  { value: "social_worker", label: "社工" },
  { value: "software_engineer", label: "軟體工程師" },
  { value: "hardware_engineer", label: "硬體工程師" },
  { value: "it_professional", label: "資訊人員" },
  { value: "data_analyst", label: "數據分析師" },
  { value: "finance", label: "金融業" },
  { value: "insurance", label: "保險業" },
  { value: "sales", label: "業務" },
  { value: "marketing", label: "行銷" },
  { value: "hr", label: "人資" },
  { value: "management", label: "管理職" },
  { value: "designer", label: "設計師" },
  { value: "media", label: "媒體業" },
  { value: "artist", label: "藝術家" },
  { value: "content_creator", label: "內容創作者" },
  { value: "food_beverage", label: "餐飲業" },
  { value: "retail", label: "零售業" },
  { value: "tourism", label: "旅遊業" },
  { value: "beauty", label: "美容美髮" },
  { value: "hospitality", label: "飯店業" },
  { value: "manufacturing", label: "製造業" },
  { value: "construction", label: "營建業" },
  { value: "transportation", label: "運輸業" },
  { value: "technician", label: "技術人員" },
  { value: "agriculture", label: "農業" },
  { value: "freelancer", label: "自由工作者" },
  { value: "business_owner", label: "企業主" },
  { value: "startup", label: "創業者" },
  { value: "homemaker", label: "家管" },
  { value: "retired", label: "退休" },
  { value: "unemployed", label: "待業中" },
  { value: "volunteer", label: "志工" },
  { value: "other", label: "其他" },
] as const;

export const AVAILABLE_FIELDS = [
  { value: "technology_ict", label: "資訊與資訊通信科技(ICT)" },
  { value: "business_management", label: "商業與管理" },
  { value: "arts_creative_design", label: "藝術、創意與設計" },
  { value: "science_research", label: "科學與研究" },
  { value: "engineering_manufacturing", label: "工程與製造" },
  { value: "health_medicine", label: "健康與醫學" },
  { value: "education_learning", label: "教育與學習" },
  { value: "social_sciences", label: "社會科學" },
  { value: "languages", label: "語言" },
  { value: "law", label: "法律" },
  { value: "customer_service_hospitality", label: "客戶服務與餐飲" },
  { value: "agriculture_environmental_sciences", label: "農業與環境科學" },
  { value: "others", label: "其他" },
] as const;

export const INTEREST_CATEGORIES = [
  { value: "nature_environment", label: "自然與環境" },
  { value: "mathematical_logic", label: "數理與邏輯" },
  { value: "information_computer_science", label: "資訊與電腦科學" },
  { value: "languages", label: "語言" },
  { value: "humanities_history_geography", label: "人文、歷史與地理" },
  { value: "sociology_psychology", label: "社會學與心理學" },
  { value: "education_learning", label: "教育與學習" },
  { value: "business_management_finance", label: "商管與理財" },
  { value: "arts_design", label: "藝術與設計" },
  { value: "lifestyle", label: "生活風格與品味" },
  { value: "social_innovation_sustainability", label: "社會創新與永續" },
  { value: "medicine_sports", label: "醫學與運動" },
  { value: "personal_development", label: "個人成長" },
  { value: "others", label: "其他" },
] as const;

export const NOTIFICATION_TYPES = [
  { type: "reaction", label: "反應", description: "有人對你的內容按了反應" },
  { type: "comment", label: "留言與 @", description: "有人留言或 @ 提及了你" },
  { type: "follow-user", label: "關注", description: "有人關注了你" },
  { type: "connect", label: "連結請求", description: "有人向你發出連結請求" },
  { type: "agree-connect", label: "連結確認", description: "對方同意了你的連結請求" },
  { type: "update-practice-checkin", label: "關注的實踐更新", description: "你關注的實踐有新打卡" },
  { type: "practice-started", label: "關注的人開始實踐", description: "你關注的人開始了新主題實踐" },
  { type: "buddy-request", label: "Buddy 請求", description: "有人邀請你成為實踐夥伴" },
  { type: "weekly", label: "週報", description: "每週一的島嶼探索摘要" },
] as const;
