import {
  ResourceDetailResponseSchema,
  ResourceListResponseSchema,
} from "./core";
import { ResourceReviewSchema } from "./reviews";

export const mockResource: ResourceDetailResponseSchema = {
  id: 1,
  name: "回收大百科",
  url: "https://recycle.rethinktw.org/",
  imageUrl: "https://i.imgur.com/hWt9pbi.jpeg",
  description:
    "RE-THINK的目標就是解決台灣爆量的垃圾問題，身為本土最具社群號召力的環保團體，我們從2013年開始，RE-THINK帶領超過3萬群眾在全台灣淨灘。在全台海灘撿越久的垃圾，才發現牽連到的問題越多。所以，我們製作《海廢圖鑑》，用最ㄎㄧㄤ的方式把全台灣的海洋廢棄物搜集成網站，讓大家重新認識海洋廢棄物。但光了解海廢還不夠，我們生活中每天都製造了源源不絕的垃圾，其中更有不少垃圾沒有妥善被處理。於是讓大家懂分、懂丟的《回收大百科》就這麼誕生了！",
  videoUrl: "https://www.youtube.com/embed/4n66brdz1GY?si=afNRjAb0endaKIxG",
  type: "工具/操作",
  level: "學齡前,國小,國高中,大學以上",
  cost: "免費",
  status: "active",
  reviewCount: 45,
  avgRating: 4.8,
  majorCategory: "教育",
  subCategory: "生活",
  user: {
    _id: "user1",
    id: "user1",
    name: "Tiff",
    roleList: ["user", "contributor"],
    photoURL: "https://i.imgur.com/avatars/tiff.jpg",
  },
  createdAt: "2025-05-01T02:47:00.000Z",
  updatedAt: "2025-05-01T02:55:00.000Z",
  tags: ["環境保護", "垃圾", "回收", "永續發展"],
  viewCount: 1250,
  favoriteCount: 320,
  shareCount: 150,
  recentReviews: [
    {
      id: 1,
      content: "這個資源真的很好用，我已經用了好幾年了，每次使用都覺得很滿意。",
      avgRating: 5,
      createdAt: "2025-05-01T02:47:00.000Z",
      tags: ["結構清晰", "實用導向", "觀念完整"],
      user: {
        _id: "user1",
        id: "user1",
        name: "Tiff",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/tiff.jpg",
      },
      status: "active",
      likesCount: 10,
      helpfulCount: 10,
      resourceId: 1,
    },
  ],
};

export const mockResourceReview: ResourceReviewSchema = {
  id: 1,
  status: "active",
  avgRating: 5,
  user: {
    id: "user1",
    name: "Tiff",
    _id: "user1",
    roleList: ["user", "contributor"],
    photoURL: "https://i.imgur.com/avatars/tiff.jpg",
  },
  createdAt: "2025-05-01T02:47:00.000Z",
  tags: ["結構清晰", "實用導向", "觀念完整"],
  resourceId: 1,
  likesCount: 10,
  helpfulCount: 10,
  content: "這個教學寫得很清楚，步驟詳細，適合初學者...",
  overallImpact: 5,
  changeMindset: 4,
  solveProblems: 5,
  gainPerspectives: 4,
  achieveGoals: 5,
  timeUsage: "1_2_hours_daily",
  contentFeatures: {
    wellStructured: true,
    practiceFocused: true,
    wellRoundedConcepts: false,
    thoughtProvoking: true,
    progressiveLearning: false,
    problemBased: false,
    realWorldExamples: true,
    interactive: false,
    visuallyRich: true,
  },
  resourceUsage: {
    withOnlineCourses: true,
    withBooks: false,
    withOtherTools: true,
    withCommunity: false,
    onlyThisResource: false,
    notApplicableResource: false,
  },
};

export const mockResourceList: ResourceListResponseSchema = {
  resources: [
    {
      id: 1,
      name: "回收大百科",
      url: "https://recycle.rethinktw.org/",
      imageUrl: "https://i.imgur.com/hWt9pbi.jpeg",
      description:
        "RE-THINK的目標就是解決台灣爆量的垃圾問題，身為本土最具社群號召力的環保團體，我們從2013年開始，RE-THINK帶領超過3萬群眾在全台灣淨灘。在全台海灘撿越久的垃圾，才發現牽連到的問題越多。所以，我們製作《海廢圖鑑》，用最ㄎㄧㄤ的方式把全台灣的海洋廢棄物搜集成網站，讓大家重新認識海洋廢棄物。但光了解海廢還不夠，我們生活中每天都製造了源源不絕的垃圾，其中更有不少垃圾沒有妥善被處理。於是讓大家懂分、懂丟的《回收大百科》就這麼誕生了！",
      videoUrl: "https://www.youtube.com/embed/4n66brdz1GY?si=afNRjAb0endaKIxG",
      type: "工具/操作",
      level: "學齡前,國小,國高中,大學以上",
      cost: "免費",
      status: "active",
      reviewCount: 45,
      avgRating: 4.8,
      majorCategory: "教育",
      subCategory: "生活",
      user: {
        _id: "user1",
        id: "user1",
        name: "Tiff",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/tiff.jpg",
      },
      createdAt: "2025-05-01T02:47:00.000Z",
      updatedAt: "2025-05-01T02:55:00.000Z",
      tags: ["環境保護", "垃圾", "回收", "永續發展"],
      viewCount: 1250,
      favoriteCount: 320,
      shareCount: 150,
    },
    {
      id: 2,
      name: "海廢圖鑑",
      url: "https://oceantrash.rethinktw.org/",
      imageUrl: "https://i.imgur.com/8TWSSZB.jpeg",
      description: "台灣第一本海洋廢棄物圖鑑。每年有800萬公噸垃圾進入海洋，這些不速之客入侵海洋後，被海塑造成另一個模樣，最後被海浪還給我們、擱淺在海灘上。透過全台的淨灘，我們拾起這些海洋廢棄物（簡稱海廢），不單只是把它清除丟掉，而是要了解它們到底是什麼、從哪來、又會去哪？了解問題，我們才可能真的解決問題。RE-THINK 花了數個月的時間，把垃圾分門別類、360度棚拍、將生硬的資訊翻譯成白話文，跟企業夥伴、NGO夥伴協力推出台灣第一本海洋廢棄物圖鑑。",
      videoUrl: null,
      type: "工具/操作",
      level: "學齡前,國小,國高中,大學以上",
      cost: "免費",
      status: "active",
      reviewCount: 35,
      avgRating: 4.6,
      majorCategory: "教育",
      subCategory: "自然科學",
      user: {
        _id: "user1",
        id: "user1",
        name: "Tiff",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/tiff.jpg",
      },
      createdAt: "2025-05-01T02:43:00.000Z",
      updatedAt: "2025-05-01T02:55:00.000Z",
      tags: ["環境保護", "海洋", "永續發展", "垃圾"],
      viewCount: 0,
      favoriteCount: 0,
      shareCount: 0
    },
    {
      id: 3,
      name: "社會創新相關工具（教育部資科司iLink計畫）",
      url: "https://www.ilink-hss.org/Toolkits",
      imageUrl: "https://i.imgur.com/WBEqjq6.png",
      description:
        "本計畫預計提供100個Toolkits之資源給大家，包括服務設計、設計思考、商業模式、人工智慧以及軟體應用等，形式包括影音、PDF、PPT、Podcast等，透過既有資源，鏈結各團隊執行計畫所需資源，並相互合作及切磋。",
      videoUrl: null,
      type: "組織/社群,工具/操作",
      level: "國高中,大學以上",
      cost: "免費",
      status: "active",
      viewCount: 0,
      favoriteCount: 0,
      shareCount: 0,
      reviewCount: 25,
      avgRating: 4.5,
      majorCategory: "人文社會",
      subCategory: "綜合型學習資源",
      user: {
        _id: "user2",
        id: "user2",
        name: "Admin",
        roleList: ["admin", "contributor"],
        photoURL: "https://i.imgur.com/avatars/admin.jpg",
      },
      createdAt: "2025-01-09T14:37:00.000Z",
      updatedAt: "2025-01-09T14:41:00.000Z",
      tags: ["社會創新", "社會設計", "設計思考", "服務設計", "UIUX"],
    },
    {
      id: 4,
      name: "好數多",
      url: "https://lin.ee/G57Ujpg",
      imageUrl: "https://i.imgur.com/F1fPYDq.png",
      description:
        "「好數多」是致力於提供中學學生數學相關學習資源，幫助學生提升自主學習的戰鬥力，是教師備課與學生自主學習的好工具! 要使用此工具只要加入「好數多」LINE官方帳號即可立即使用，你只要輸入不懂的數學概念名稱，它就會自動推薦講解影片，非常方便。此服務完全免費，是可以多加善用的自主學習工具！",
      videoUrl: "https://youtu.be/qPeLcZRv-jI",
      type: "工具/操作",
      level: "國高中",
      cost: "免費",
      status: "active",
      viewCount: 0,
      favoriteCount: 0,
      shareCount: 0,
      reviewCount: 75,
      avgRating: 4.9,
      majorCategory: "數學與邏輯",
      subCategory: "數學工具",
      user: {
        _id: "user3",
        id: "user3",
        name: "Tim",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/tim.jpg",
      },
      createdAt: "2025-01-01T10:55:00.000Z",
      updatedAt: "2025-01-01T10:58:00.000Z",
      tags: ["數學"],
    },
    {
      id: 5,
      name: "友善校園學生事務與輔導工作資訊網",
      url: "https://friendlycampus.k12ea.gov.tw/Portal",
      imageUrl: "https://i.imgur.com/H5JZQC7.png",
      description:
        "提供各類有益於國中生、高中職學生之生涯輔導相關資源連結及生涯輔導Q&A，協助學生探索自我、了解興趣、發展潛能。",
      videoUrl: null,
      type: "課程/活動,組織/社群",
      level: "國高中,大學以上",
      cost: "免費",
      status: "active",
      viewCount: 0,
      favoriteCount: 0,
      shareCount: 0,
      reviewCount: 28,
      avgRating: 4.2,
      majorCategory: "教育",
      subCategory: "綜合型學習資源",
      user: {
        _id: "user3",
        id: "user3",
        name: "Tim",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/tim.jpg",
      },
      createdAt: "2025-01-01T10:52:00.000Z",
      updatedAt: "2025-01-01T10:55:00.000Z",
      tags: ["生涯探索", "社會議題", "生命教育", "諮商", "性別平等"],
    },
    {
      id: 6,
      name: "台灣開放式課程平台",
      url: "https://www.tocec.org.tw/web/index.jsp",
      imageUrl: "https://i.imgur.com/JK8L32p.png",
      description:
        "台灣開放式課程平台提供各大學優質的課程錄影和講義資源，免費供大眾自主學習。涵蓋人文、社會、理工、藝術等多元領域，讓學習不受時間與空間限制。",
      videoUrl: null,
      type: "課程/活動",
      level: "大學以上",
      cost: "免費",
      status: "active",
      viewCount: 0,
      favoriteCount: 0,
      shareCount: 0,
      reviewCount: 87,
      avgRating: 4.7,
      majorCategory: "教育",
      subCategory: "綜合型學習資源",
      user: {
        _id: "user4",
        id: "user4",
        name: "Sophie",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/sophie.jpg",
      },
      createdAt: "2024-12-15T08:22:00.000Z",
      updatedAt: "2024-12-15T08:30:00.000Z",
      tags: ["開放式課程", "自主學習", "線上教育", "高等教育"],
    },
    {
      id: 7,
      name: "C語言教學資源",
      url: "https://programming.im.ncnu.edu.tw/C_index.html",
      imageUrl: "https://i.imgur.com/Pn2XQc7.jpeg",
      description:
        "由國立暨南國際大學教授提供的免費C語言教學網站，包含豐富的教材、範例程式和練習題。適合程式設計初學者或想要精進C語言能力的學生使用。",
      videoUrl: "https://youtu.be/example-c-programming",
      type: "課程/活動,工具/操作",
      level: "國高中,大學以上",
      cost: "免費",
      status: "active",
      viewCount: 0,
      favoriteCount: 0,
      shareCount: 0,
      reviewCount: 123,
      avgRating: 4.8,
      majorCategory: "科技",
      subCategory: "程式設計",
      user: {
        _id: "user5",
        id: "user5",
        name: "David",
        roleList: ["user", "contributor", "educator"],
        photoURL: "https://i.imgur.com/avatars/david.jpg",
      },
      createdAt: "2024-11-30T15:40:00.000Z",
      updatedAt: "2024-11-30T15:48:00.000Z",
      tags: ["程式設計", "C語言", "資訊教育", "電腦科學"],
    },
    {
      id: 8,
      name: "台灣生態教育資源網",
      url: "https://ecolearn.tw",
      imageUrl: "https://i.imgur.com/NMR5Tf7.jpeg",
      description:
        "台灣生態教育資源網整合了台灣各地的生態教育資源，包括自然保護區、野生動植物、海洋生態等資訊。網站提供教案、影片、圖鑑和互動教材，適合教師、學生和生態愛好者使用。",
      videoUrl: "https://youtu.be/taiwan-eco-intro",
      type: "組織/社群,工具/操作",
      level: "學齡前,國小,國高中,大學以上",
      cost: "免費",
      status: "active",
      viewCount: 0,
      favoriteCount: 0,
      shareCount: 0,
      reviewCount: 92,
      avgRating: 4.9,
      majorCategory: "教育",
      subCategory: "自然科學",
      user: {
        _id: "user6",
        id: "user6",
        name: "Lily",
        roleList: ["user", "contributor", "environmentalist"],
        photoURL: "https://i.imgur.com/avatars/lily.jpg",
      },
      createdAt: "2024-11-05T09:15:00.000Z",
      updatedAt: "2024-11-05T09:22:00.000Z",
      tags: ["生態教育", "環境保護", "生物多樣性", "自然保育", "戶外教學"],
    },
    {
      id: 9,
      name: "藝術治療資源庫",
      url: "https://artstherapy.org.tw",
      imageUrl: "https://i.imgur.com/L7PqTs4.jpeg",
      description:
        "藝術治療資源庫提供各類藝術治療相關資源，包括理論基礎、案例分享、實務工具和技巧介紹。適合心理健康專業人員、藝術治療師、教育工作者和對藝術治療有興趣的一般大眾。",
      videoUrl: null,
      type: "組織/社群,工具/操作",
      level: "大學以上",
      cost: "部分免費",
      status: "active",
      viewCount: 0,
      favoriteCount: 0,
      shareCount: 0,
      reviewCount: 65,
      avgRating: 4.6,
      majorCategory: "藝術與人文",
      subCategory: "心理健康",
      user: {
        _id: "user7",
        id: "user7",
        name: "Grace",
        roleList: ["user", "contributor", "therapist"],
        photoURL: "https://i.imgur.com/avatars/grace.jpg",
      },
      createdAt: "2024-10-20T13:40:00.000Z",
      updatedAt: "2024-10-20T13:48:00.000Z",
      tags: ["藝術治療", "心理健康", "表達性藝術", "創作治療", "心理諮商"],
    },
    {
      id: 10,
      name: "科學實驗資源平台",
      url: "https://sciencelab.edu.tw",
      imageUrl: "https://i.imgur.com/XZ7YpQr.jpeg",
      description:
        "科學實驗資源平台彙整了各種適合中小學生的科學實驗教材和指引，包括物理、化學、生物和地球科學等領域。提供詳細的實驗步驟、所需材料、安全注意事項和背後的科學原理解釋。",
      videoUrl: "https://youtu.be/science-lab-intro",
      type: "工具/操作,課程/活動",
      level: "國小,國高中",
      cost: "免費",
      status: "active",
      viewCount: 0,
      favoriteCount: 0,
      shareCount: 0,
      reviewCount: 104,
      avgRating: 4.8,
      majorCategory: "科學",
      subCategory: "實驗教育",
      user: {
        _id: "user8",
        id: "user8",
        name: "Kevin",
        roleList: ["user", "contributor", "educator"],
        photoURL: "https://i.imgur.com/avatars/kevin.jpg",
      },
      createdAt: "2024-09-12T10:20:00.000Z",
      updatedAt: "2024-09-12T10:28:00.000Z",
      tags: ["科學實驗", "動手做", "STEM教育", "實驗教學", "科學教育"],
    },
  ],
  pagination: {
    limit: 10,
    hasNext: true,
    hasPrev: false,
    nextCursor: "7b707fb7-311b-4ffa-9582-80990c91205d",
    prevCursor: null,
    totalEstimate: 25,
  },
};
