export const mockResourceList = {
  resources: [
    {
      id: 1,
      resourceName: "回收大百科",
      resourceUrl: "https://recycle.rethinktw.org/",
      resourceImgUrl: "https://i.imgur.com/hWt9pbi.jpeg",
      description: "RE-THINK的目標就是解決台灣爆量的垃圾問題，身為本土最具社群號召力的環保團體，我們從2013年開始，RE-THINK帶領超過3萬群眾在全台灣淨灘。在全台海灘撿越久的垃圾，才發現牽連到的問題越多。所以，我們製作《海廢圖鑑》，用最ㄎㄧㄤ的方式把全台灣的海洋廢棄物搜集成網站，讓大家重新認識海洋廢棄物。但光了解海廢還不夠，我們生活中每天都製造了源源不絕的垃圾，其中更有不少垃圾沒有妥善被處理。於是讓大家懂分、懂丟的《回收大百科》就這麼誕生了！",
      introVideoUrl: null,
      resourceType: "工具/操作",
      targetAudience: "學齡前,國小,國高中,大學以上",
      learningDuration: "不限",
      cost: "免費",
      language: "中文",
      status: "active",
      qualityScore: null,
      viewCount: 1250,
      favoriteCount: 320,
      shareCount: 150,
      reviewCount: 45,
      avgRating: 4.8,
      majorCategory: "教育",
      subCategory: "生活",
      user: {
        _id: "user1",
        id: "user1",
        name: "Tiff",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/tiff.jpg"
      },
      createdAt: "2025-05-01T02:47:00.000Z",
      updatedAt: "2025-05-01T02:55:00.000Z",
      tags: ["環境保護", "垃圾", "回收", "永續發展"]
    },
    {
      id: 2,
      resourceName: "海廢圖鑑",
      resourceUrl: "https://oceantrash.rethinktw.org/",
      resourceImgUrl: "https://i.imgur.com/8TWSSZB.jpeg",
      description: "台灣第一本海洋廢棄物圖鑑。每年有800萬公噸垃圾進入海洋，這些不速之客入侵海洋後，被海塑造成另一個模樣，最後被海浪還給我們、擱淺在海灘上。透過全台的淨灘，我們拾起這些海洋廢棄物（簡稱海廢），不單只是把它清除丟掉，而是要了解它們到底是什麼、從哪來、又會去哪？了解問題，我們才可能真的解決問題。RE-THINK 花了數個月的時間，把垃圾分門別類、360度棚拍、將生硬的資訊翻譯成白話文，跟企業夥伴、NGO夥伴協力推出台灣第一本海洋廢棄物圖鑑。",
      introVideoUrl: null,
      resourceType: "工具/操作",
      targetAudience: "學齡前,國小,國高中,大學以上",
      learningDuration: "不限",
      cost: "免費",
      language: "中文",
      status: "active",
      qualityScore: null,
      viewCount: 980,
      favoriteCount: 280,
      shareCount: 120,
      reviewCount: 35,
      avgRating: 4.6,
      majorCategory: "教育",
      subCategory: "自然科學",
      user: {
        _id: "user1",
        id: "user1",
        name: "Tiff",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/tiff.jpg"
      },
      createdAt: "2025-05-01T02:43:00.000Z",
      updatedAt: "2025-05-01T02:55:00.000Z",
      tags: ["環境保護", "海洋", "永續發展", "垃圾"]
    },
    {
      id: 3,
      resourceName: "社會創新相關工具（教育部資科司iLink計畫）",
      resourceUrl: "https://www.ilink-hss.org/Toolkits",
      resourceImgUrl: "https://i.imgur.com/WBEqjq6.png",
      description: "本計畫預計提供100個Toolkits之資源給大家，包括服務設計、設計思考、商業模式、人工智慧以及軟體應用等，形式包括影音、PDF、PPT、Podcast等，透過既有資源，鏈結各團隊執行計畫所需資源，並相互合作及切磋。",
      introVideoUrl: null,
      resourceType: "組織/社群,工具/操作",
      targetAudience: "國高中,大學以上",
      learningDuration: "不限",
      cost: "免費",
      language: "中文",
      status: "active",
      qualityScore: null,
      viewCount: 765,
      favoriteCount: 185,
      shareCount: 90,
      reviewCount: 25,
      avgRating: 4.5,
      majorCategory: "人文社會",
      subCategory: "綜合型學習資源",
      user: {
        _id: "user2",
        id: "user2",
        name: "Admin",
        roleList: ["admin", "contributor"],
        photoURL: "https://i.imgur.com/avatars/admin.jpg"
      },
      createdAt: "2025-01-09T14:37:00.000Z",
      updatedAt: "2025-01-09T14:41:00.000Z",
      tags: ["社會創新", "社會設計", "設計思考", "服務設計", "UIUX"]
    },
    {
      id: 4,
      resourceName: "好數多",
      resourceUrl: "https://lin.ee/G57Ujpg",
      resourceImgUrl: "https://i.imgur.com/F1fPYDq.png",
      description: "「好數多」是致力於提供中學學生數學相關學習資源，幫助學生提升自主學習的戰鬥力，是教師備課與學生自主學習的好工具! 要使用此工具只要加入「好數多」LINE官方帳號即可立即使用，你只要輸入不懂的數學概念名稱，它就會自動推薦講解影片，非常方便。此服務完全免費，是可以多加善用的自主學習工具！",
      introVideoUrl: "https://youtu.be/qPeLcZRv-jI",
      resourceType: "工具/操作",
      targetAudience: "國高中",
      learningDuration: "不限",
      cost: "免費",
      language: "中文",
      status: "active",
      qualityScore: null,
      viewCount: 1580,
      favoriteCount: 420,
      shareCount: 230,
      reviewCount: 75,
      avgRating: 4.9,
      majorCategory: "數學與邏輯",
      subCategory: "數學工具",
      user: {
        _id: "user3",
        id: "user3",
        name: "Tim",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/tim.jpg"
      },
      createdAt: "2025-01-01T10:55:00.000Z",
      updatedAt: "2025-01-01T10:58:00.000Z",
      tags: ["數學"]
    },
    {
      id: 5,
      resourceName: "友善校園學生事務與輔導工作資訊網",
      resourceUrl: "https://friendlycampus.k12ea.gov.tw/Portal",
      resourceImgUrl: "https://i.imgur.com/H5JZQC7.png",
      description: "提供各類有益於國中生、高中職學生之生涯輔導相關資源連結及生涯輔導Q&A，協助學生探索自我、了解興趣、發展潛能。",
      introVideoUrl: null,
      resourceType: "課程/活動,組織/社群",
      targetAudience: "國高中,大學以上",
      learningDuration: "不限",
      cost: "免費",
      language: "中文",
      status: "active",
      qualityScore: null,
      viewCount: 620,
      favoriteCount: 180,
      shareCount: 95,
      reviewCount: 28,
      avgRating: 4.2,
      majorCategory: "教育",
      subCategory: "綜合型學習資源",
      user: {
        _id: "user3",
        id: "user3",
        name: "Tim",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/tim.jpg"
      },
      createdAt: "2025-01-01T10:52:00.000Z",
      updatedAt: "2025-01-01T10:55:00.000Z",
      tags: ["生涯探索", "社會議題", "生命教育", "諮商", "性別平等"]
    },
    {
      id: 6,
      resourceName: "台灣開放式課程平台",
      resourceUrl: "https://www.tocec.org.tw/web/index.jsp",
      resourceImgUrl: "https://i.imgur.com/JK8L32p.png",
      description: "台灣開放式課程平台提供各大學優質的課程錄影和講義資源，免費供大眾自主學習。涵蓋人文、社會、理工、藝術等多元領域，讓學習不受時間與空間限制。",
      introVideoUrl: null,
      resourceType: "課程/活動",
      targetAudience: "大學以上",
      learningDuration: "10-20小時",
      cost: "免費",
      language: "中文",
      status: "active",
      qualityScore: 8.7,
      viewCount: 2150,
      favoriteCount: 560,
      shareCount: 320,
      reviewCount: 87,
      avgRating: 4.7,
      majorCategory: "教育",
      subCategory: "綜合型學習資源",
      user: {
        _id: "user4",
        id: "user4",
        name: "Sophie",
        roleList: ["user", "contributor"],
        photoURL: "https://i.imgur.com/avatars/sophie.jpg"
      },
      createdAt: "2024-12-15T08:22:00.000Z",
      updatedAt: "2024-12-15T08:30:00.000Z",
      tags: ["開放式課程", "自主學習", "線上教育", "高等教育"]
    },
    {
      id: 7,
      resourceName: "C語言教學資源",
      resourceUrl: "https://programming.im.ncnu.edu.tw/C_index.html",
      resourceImgUrl: "https://i.imgur.com/Pn2XQc7.jpeg",
      description: "由國立暨南國際大學教授提供的免費C語言教學網站，包含豐富的教材、範例程式和練習題。適合程式設計初學者或想要精進C語言能力的學生使用。",
      introVideoUrl: "https://youtu.be/example-c-programming",
      resourceType: "課程/活動,工具/操作",
      targetAudience: "國高中,大學以上",
      learningDuration: "20-40小時",
      cost: "免費",
      language: "中文",
      status: "active",
      qualityScore: 9.1,
      viewCount: 3280,
      favoriteCount: 890,
      shareCount: 430,
      reviewCount: 123,
      avgRating: 4.8,
      majorCategory: "科技",
      subCategory: "程式設計",
      user: {
        _id: "user5",
        id: "user5",
        name: "David",
        roleList: ["user", "contributor", "educator"],
        photoURL: "https://i.imgur.com/avatars/david.jpg"
      },
      createdAt: "2024-11-30T15:40:00.000Z",
      updatedAt: "2024-11-30T15:48:00.000Z",
      tags: ["程式設計", "C語言", "資訊教育", "電腦科學"]
    },
    {
      id: 8,
      resourceName: "台灣生態教育資源網",
      resourceUrl: "https://ecolearn.tw",
      resourceImgUrl: "https://i.imgur.com/NMR5Tf7.jpeg",
      description: "台灣生態教育資源網整合了台灣各地的生態教育資源，包括自然保護區、野生動植物、海洋生態等資訊。網站提供教案、影片、圖鑑和互動教材，適合教師、學生和生態愛好者使用。",
      introVideoUrl: "https://youtu.be/taiwan-eco-intro",
      resourceType: "組織/社群,工具/操作",
      targetAudience: "學齡前,國小,國高中,大學以上",
      learningDuration: "不限",
      cost: "免費",
      language: "中文",
      status: "active",
      qualityScore: 9.3,
      viewCount: 1870,
      favoriteCount: 550,
      shareCount: 310,
      reviewCount: 92,
      avgRating: 4.9,
      majorCategory: "教育",
      subCategory: "自然科學",
      user: {
        _id: "user6",
        id: "user6",
        name: "Lily",
        roleList: ["user", "contributor", "environmentalist"],
        photoURL: "https://i.imgur.com/avatars/lily.jpg"
      },
      createdAt: "2024-11-05T09:15:00.000Z",
      updatedAt: "2024-11-05T09:22:00.000Z",
      tags: ["生態教育", "環境保護", "生物多樣性", "自然保育", "戶外教學"]
    },
    {
      id: 9,
      resourceName: "藝術治療資源庫",
      resourceUrl: "https://artstherapy.org.tw",
      resourceImgUrl: "https://i.imgur.com/L7PqTs4.jpeg",
      description: "藝術治療資源庫提供各類藝術治療相關資源，包括理論基礎、案例分享、實務工具和技巧介紹。適合心理健康專業人員、藝術治療師、教育工作者和對藝術治療有興趣的一般大眾。",
      introVideoUrl: null,
      resourceType: "組織/社群,工具/操作",
      targetAudience: "大學以上",
      learningDuration: "不限",
      cost: "部分免費",
      language: "中文",
      status: "active",
      qualityScore: 8.5,
      viewCount: 1290,
      favoriteCount: 420,
      shareCount: 240,
      reviewCount: 65,
      avgRating: 4.6,
      majorCategory: "藝術與人文",
      subCategory: "心理健康",
      user: {
        _id: "user7",
        id: "user7",
        name: "Grace",
        roleList: ["user", "contributor", "therapist"],
        photoURL: "https://i.imgur.com/avatars/grace.jpg"
      },
      createdAt: "2024-10-20T13:40:00.000Z",
      updatedAt: "2024-10-20T13:48:00.000Z",
      tags: ["藝術治療", "心理健康", "表達性藝術", "創作治療", "心理諮商"]
    },
    {
      id: 10,
      resourceName: "科學實驗資源平台",
      resourceUrl: "https://sciencelab.edu.tw",
      resourceImgUrl: "https://i.imgur.com/XZ7YpQr.jpeg",
      description: "科學實驗資源平台彙整了各種適合中小學生的科學實驗教材和指引，包括物理、化學、生物和地球科學等領域。提供詳細的實驗步驟、所需材料、安全注意事項和背後的科學原理解釋。",
      introVideoUrl: "https://youtu.be/science-lab-intro",
      resourceType: "工具/操作,課程/活動",
      targetAudience: "國小,國高中",
      learningDuration: "1-5小時",
      cost: "免費",
      language: "中文",
      status: "active",
      qualityScore: 9.0,
      viewCount: 2450,
      favoriteCount: 680,
      shareCount: 370,
      reviewCount: 104,
      avgRating: 4.8,
      majorCategory: "科學",
      subCategory: "實驗教育",
      user: {
        _id: "user8",
        id: "user8",
        name: "Kevin",
        roleList: ["user", "contributor", "educator"],
        photoURL: "https://i.imgur.com/avatars/kevin.jpg"
      },
      createdAt: "2024-09-12T10:20:00.000Z",
      updatedAt: "2024-09-12T10:28:00.000Z",
      tags: ["科學實驗", "動手做", "STEM教育", "實驗教學", "科學教育"]
    }
  ],
  pagination: {
    limit: 10,
    hasNext: true,
    hasPrev: false,
    nextCursor: "7b707fb7-311b-4ffa-9582-80990c91205d",
    prevCursor: null,
    totalEstimate: 25
  }
};
