/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Metrics
     * @description Endpoint that serves Prometheus metrics.
     */
    get: operations["metrics_metrics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/feed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Feed
     * @description 混合 practice + checkin 的 feed 列表（infinite scroll）
     */
    get: operations["get_feed_api_v1_feed_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recommendation/rank_feed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Recommendation Feed
     * @description 推薦 feed API
     *     - JWT 驗證透過 get_current_user 自動處理
     *     example:
     *     curl -X POST "http://localhost:8002/api/recommendation/rank_feed?limit=10"     -H "accept: application/json"     -H "Authorization: Bearer <YOUR_TOKEN_ID>"
     */
    get: operations["recommendation_feed_api_v1_recommendation_rank_feed_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/practices/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Practice Suggestions
     * @description 取得搜尋建議關鍵字（近期熱門標籤 + 我的技能興趣相關標籤）
     */
    get: operations["get_practice_suggestions_api_v1_users_practices_suggestions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/practices/completions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Practice Completions
     * @description 關鍵字文字補全與預測下一個詞（輸入框即時補全用）
     */
    get: operations["get_practice_completions_api_v1_users_practices_completions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/practices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get My Practices
     * @description 取得使用者的實踐貼文列表
     */
    get: operations["get_my_practices_api_v1_users_practices_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ping
     * @description Simple ping endpoint for basic connectivity tests.
     */
    get: operations["ping_api_v1_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Comprehensive health check endpoint for monitoring and load balancer probes.
     *
     *     :returns: Service health status with version and connectivity checks
     *     :rtype: HealthResponse
     */
    get: operations["health_check_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root */
    get: operations["root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * FeedReasonType
     * @enum {string}
     */
    FeedReasonType: "new_practice" | "new_release" | "checked_in" | "cheered";
    /** APIResponse */
    APIResponse: {
      /** Success */
      success: boolean;
      /** Data */
      data?: unknown | null;
      error?: components["schemas"]["ErrorInfo"] | null;
      pagination?: components["schemas"]["CursorPaginationInfo"] | null;
      /** Timestamp */
      timestamp: string;
      /** Requestid */
      requestId: string;
      /**
       * Cachehit
       * @default false
       */
      cacheHit: boolean;
      /**
       * Processingtime
       * @default 0
       */
      processingTime: number;
    };
    /** CursorInfo */
    CursorInfo: {
      /** Start */
      start?: string | null;
      /** End */
      end?: string | null;
    };
    /** CursorPaginationInfo */
    CursorPaginationInfo: {
      cursors?: components["schemas"]["CursorInfo"] | null;
      /**
       * Hasprev
       * @default false
       */
      hasPrev: boolean | null;
      /**
       * Hasnext
       * @default false
       */
      hasNext: boolean | null;
      /**
       * Count
       * @default 0
       */
      count: number | null;
    };
    /** ErrorInfo */
    ErrorInfo: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /** Details */
      details?: {
        [key: string]: unknown;
      } | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description Health check response model.
     * @example {
     *       "environment": "development",
     *       "service_name": "rag-api",
     *       "services": {
     *         "database": {
     *           "message": "Connected successfully",
     *           "status": "healthy"
     *         },
     *         "pdf_parser": {
     *           "message": "Docling parser ready",
     *           "status": "healthy"
     *         }
     *       },
     *       "status": "ok",
     *       "version": "0.1.0"
     *     }
     */
    HealthResponse: {
      /**
       * Status
       * @description Overall health status
       * @example ok
       */
      status: string;
      /**
       * Version
       * @description Application version
       * @example 0.1.0
       */
      version: string;
      /**
       * Environment
       * @description Deployment environment
       * @example development
       */
      environment: string;
      /**
       * Service Name
       * @description Service identifier
       * @example rag-api
       */
      service_name: string;
      /**
       * Services
       * @description Individual service statuses
       */
      services?: {
        [key: string]: components["schemas"]["ServiceStatus"];
      } | null;
    };
    /**
     * ServiceStatus
     * @description Individual service status.
     */
    ServiceStatus: {
      /**
       * Status
       * @description Service status
       * @example healthy
       */
      status: string;
      /**
       * Message
       * @description Status message
       * @example Connected successfully
       */
      message?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_feed_api_v1_feed_get: {
    parameters: {
      query?: {
        /** @description 關鍵字搜尋 */
        keyword?: string | null;
        /** @description 標籤篩選 */
        tags?: string[] | null;
        /** @description feed 類型（all / practice / checkin） */
        type?: string | null;
        /** @description cursor-based 分頁 */
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  metrics_metrics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  recommendation_feed_api_v1_recommendation_rank_feed_get: {
    parameters: {
      query?: {
        /** @description 上一次最後一筆的 id，作為 cursor */
        after_id?: number | null;
        /** @description 每頁抓幾筆 */
        page_size?: number;
        /** @description 要抓哪些類型的 feed */
        type?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_practice_suggestions_api_v1_users_practices_suggestions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIResponse"];
        };
      };
    };
  };
  get_practice_completions_api_v1_users_practices_completions_get: {
    parameters: {
      query: {
        /** @description 輸入前綴或完整詞 */
        q: string;
        /** @description 最多回傳幾個候選詞 */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_my_practices_api_v1_users_practices_get: {
    parameters: {
      query?: {
        limit?: number;
        /** @description 上一次最後一筆的 id，作為 cursor */
        after_id?: number | null;
        offset?: number;
        /** @description 多維度關鍵字搜尋（標題、行動、標籤、資源、打卡內容） */
        keyword?: string | null;
        tags?: string[] | null;
        duration_min?: number | null;
        duration_max?: number | null;
        status?: string | null;
        /** @description newest_updated | oldest_updated | newest_created | oldest_created| recommended */
        sort_by?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  ping_api_v1_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  health_check_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
