name: CI and Deploy workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "**"
      - "!dependabot/**"
  workflow_dispatch:

env:
  PR_URL: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}

jobs:
  init:
    name: Initial Common Steps
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: lint
        run: |
          yarn lint
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit lint Changes
        if: env.changes == 'true'
        run: |
          git commit -m "chore: format code"
          git push

  build_and_deploy:
    name: Build and Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30
    needs: lint

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn pages:build

      - name: Deploy to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy --branch=${{ github.event.pull_request.head.ref }}

    outputs:
      preview-url: ${{ steps.deploy.outputs.pages-deployment-alias-url }}

  send_result:
    name: Send Result
    runs-on: ubuntu-latest
    needs: [lint, build_and_deploy]
    if: always()

    steps:
      - uses: actions/checkout@v3

      - name: Send Lint Failed Notification
        if: ${{ needs.lint.result == 'failure' }}
        uses: ./.github/actions/notification
        with:
          TYPE: failure
          TITLE: "❌ Lint Failed"
          DESCRIPTION: "PR Link: [PR #${{ github.event.number }}](${{ env.PR_URL }})"
          DISCORD_WEBHOOK_URL: ${{ secrets.SANDBOX_DISCORD_WEBHOOK_URL }}

      - name: Send Build and Deploy Failed Notification
        if: ${{ needs.build_and_deploy.result == 'failure' }}
        uses: ./.github/actions/notification
        with:
          TYPE: failure
          TITLE: "❌ Build and Deploy Failed"
          DESCRIPTION: "PR Link: [PR #${{ github.event.number }}](${{ env.PR_URL }})"
          DISCORD_WEBHOOK_URL: ${{ secrets.SANDBOX_DISCORD_WEBHOOK_URL }}

      - name: Send Build Succeeded Notification
        if: ${{ needs.build_and_deploy.result == 'success' }}
        uses: ./.github/actions/notification
        with:
          TYPE: success
          TITLE: "✅ Build Succeeded"
          DESCRIPTION: "Preview URL: ${{ needs.build_and_deploy.outputs.preview-url }}"
          DISCORD_WEBHOOK_URL: ${{ secrets.SANDBOX_DISCORD_WEBHOOK_URL }}
