name: Continuous Integration

concurrency:
  group: ci-${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:

env:
  PR_URL: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  IS_INTERNAL_PR: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

jobs:
  init:
    name: Initial Common Steps
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('package.json', '**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  check:
    name: TypeScript Check
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: TypeScript Check
        id: check
        run: |
          if ! ERROR_MSG=$(yarn ts:check 2>&1); then
              {
                echo "check_error<<EOF"
                echo "$ERROR_MSG"
                echo "EOF"
              } >> $GITHUB_OUTPUT
              exit 1
          fi

      - name: Send TypeScript Error Notification
        if: steps.check.outcome == 'failure' && env.IS_INTERNAL_PR == 'true'
        uses: ./.github/actions/notification
        with:
          TYPE: failure
          TITLE: "❌ TypeScript Error"
          DESCRIPTION: "Branch: ${{ env.BRANCH_NAME }}\n\n${{ steps.check.outputs.check_error }}"
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Check on failure
        if: steps.check.outcome == 'failure'
        env:
          CHECK_ERROR: ${{ steps.check.outputs.check_error }}
        run: |
          echo "❌ TypeScript Error"
          echo $CHECK_ERROR
          exit 1

  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: ESLint Check
        id: lint
        continue-on-error: true
        run: |
          if ! ERROR_MSG=$(yarn lint 2>&1); then
              {
                echo "lint_error<<EOF"
                echo "$ERROR_MSG"
                echo "EOF"
              } >> $GITHUB_OUTPUT
              exit 1
          fi

      - name: Send ESLint Error Notification
        if: steps.lint.outcome == 'failure' && env.IS_INTERNAL_PR == 'true'
        uses: ./.github/actions/notification
        with:
          TYPE: failure
          TITLE: "❌ Lint Failed"
          DESCRIPTION: "Branch: ${{ env.BRANCH_NAME }}\n\n${{ steps.lint.outputs.lint_error }}"
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Check on failure
        if: steps.lint.outcome == 'failure'
        env:
          LINT_ERROR: ${{ steps.lint.outputs.lint_error }}
        run: |
          echo "❌ Lint Failed"
          echo $LINT_ERROR
          exit 1
