name: Continuous Integration

concurrency:
  group: ci-${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - 'prod'
    types:
      - opened

  workflow_call:
  workflow_dispatch:

env:
  PR_URL: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  HUSKY: 0

jobs:
  init:
    name: Initial Common Steps
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: TypeScript Check
        id: typecheck
        continue-on-error: true
        run: |
          if ! ERROR_MSG=$(pnpm typecheck 2>&1); then
              {
                echo "typecheck_error<<EOF"
                echo "$ERROR_MSG"
                echo "EOF"
              } >> $GITHUB_OUTPUT
              exit 1
          fi

      - name: Send TypeScript Error Notification
        if: steps.typecheck.outcome == 'failure'
        uses: ./.github/actions/notification
        with:
          TYPE: failure
          TITLE: "❌ TypeScript Error"
          DESCRIPTION: "Branch: ${{ env.BRANCH_NAME }}\n\n${{ steps.typecheck.outputs.typecheck_error }}"
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Check on failure
        if: steps.typecheck.outcome == 'failure'
        env:
          TYPECHECK_ERROR: ${{ steps.typecheck.outputs.typecheck_error }}
        run: |
          echo "❌ TypeScript Error"
          echo $TYPECHECK_ERROR
          exit 1

  quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Code Quality Check
        id: quality
        continue-on-error: true
        run: |
          if ! ERROR_MSG=$(pnpm check 2>&1); then
              {
                echo "quality_error<<EOF"
                echo "$ERROR_MSG"
                echo "EOF"
              } >> $GITHUB_OUTPUT
              exit 1
          fi

      - name: Send Code Quality Error Notification
        if: steps.quality.outcome == 'failure'
        uses: ./.github/actions/notification
        with:
          TYPE: failure
          TITLE: "❌ Code Quality Check Failed"
          DESCRIPTION: "Branch: ${{ env.BRANCH_NAME }}\n\n${{ steps.quality.outputs.quality_error }}"
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Check on failure
        if: steps.quality.outcome == 'failure'
        env:
          QUALITY_ERROR: ${{ steps.quality.outputs.quality_error }}
        run: |
          echo "❌ Code Quality Check Failed"
          echo $QUALITY_ERROR
          exit 1
