name: PR Notification

on:
  pull_request:
    branches: "**"

env:
  TITLE: "## ${{ github.event.pull_request.title }}"
  PR_LINK: "PR Link: [PR #${{ github.event.number }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }})"
  DESCRIPTION: "${{ github.event.pull_request.body || 'No description' }}"

jobs:
  send_notification:
    name: Send Notification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Send PR Notification
        uses: ./.github/actions/notification
        with:
          TYPE: info
          TITLE: "🔔 ${{ env.TITLE }}"
          DESCRIPTION: "${{ env.PR_LINK }}\\n\\n${{ env.DESCRIPTION }}"
          AUTHOR_NAME: ${{ github.event.pull_request.user.name || github.event.pull_request.user.login }}
          AUTHOR_ICON_URL: ${{ github.event.pull_request.user.avatar_url }}
          DISCORD_WEBHOOK_URL: ${{ secrets.SANDBOX_DISCORD_WEBHOOK_URL }}
