name: Update i18n

on:
  workflow_dispatch:

jobs:
  update_i18n:
    name: Update i18n Translations
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Fetch i18n Translations
        run: pnpm i18n:fetch

      - name: Check for i18n changes
        id: check_changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add constants/locales
          git diff --cached --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit i18n Changes
        if: success() && steps.check_changes.outputs.changes == 'true'
        run: |
          git commit -m "i18n: update translations"
          git push
